### ISSUE TITLE
System Design

### ISSUE THREAD

**Issue by ryankennedyio** [mhallsmoore/qstrader#102]
A few thoughts today to have come out from this. This can get locked down as we move closer to a Beta version with proper documentation, etc. Main thing would just be that we want clean & lean interfaces. 

(used draw.io -- simple XML (import & export)[https://raw.githubusercontent.com/ryankennedyio/qstrader/sys-diagrams/system-design.xml])

![qstrader](https://cloud.githubusercontent.com/assets/11158006/17076413/150e09aa-50f0-11e6-9c66-794d254600f6.png)

Statistics should have a link to PriceParser, but actually PriceParser needlessly adds things to this diagram. Also the direction of some arrows is currently incorrect (e.g. Statistics pulls from PortfolioHandler, but PortfolioHandler can't push to Statistics)

Just visually, PortfolioHandler and Backtest share a lot of the same moving parts (Strategy, PositionSizer, RiskManager, Statistics, PriceHandler). This is pretty necessary though. Should help a bit with seeing how we can tackle #91 correctly.

**Comment by muke5hy** [comment]
@ryankennedyio looking at the diagram it seems the system is moving towards only backtest. In case of live trading scenario we will be calling backtest file? 

NOTE: I'm still trying to understand the complete flow.

**Comment by femtotrader** [comment]
@ryankennedyio nice diagram!

@muke5hy 
Same https://github.com/mhallsmoore/qstrader/issues/62

in fact `Backtest` should be `TradingSession`

(every `trading_session` will inherit `AbstractTradingSession`)

Some `trading_session` could be `Live`, `PaperTrade` and of course `Backtest`

all these `trading_session` will have a `run` method

see in my project https://github.com/femtotrader/femtotrading/tree/master/femtotrading/trading_session
where we might go...

**Comment by muke5hy** [comment]
@femtotrader your implementation seems logical. Can we have this in QsTrader ? @ryankennedyio What's your point in this?

**Comment by ryankennedyio** [comment]
Sorry yes, Backtest should be TradingSession. Anyone is welcome to load that .xml file into draw.io and make any revisions.

Further, I'm not really sure if we can find a better name for the "working files" ?

I also noticed we can move the Statistics graphing out of TradingSession and into the "Working Files". It's not really the responsibility of the TradingSession to tell us how it went -- we should be asking it for output.


@muke5hy @femtotrader I think that's the best way to move forward with Live/Demo trading. Will probably be up to whoever starts working on it first with a real account, to start implementation.

I'm still working through the small refactor of Portfolio/Position handling with closed positions.



We can probably remove a lot of the above arrows by getting the TradingSession to "get" certain components "through" the PortfolioHandler.

This way the TradingSession is much more obviously defined as an interface between the EventQueue loop and the Portfolio, rather than being 'linked' to many of the parts that we can get from the PortfolioHandler.

**Comment by femtotrader** [comment]
For paper trade / live trade we could use https://github.com/ig-python/ig-markets-api-python-library
