### ISSUE TITLE
Data cleanup and reorganization

### ISSUE THREAD

**Issue by femtotrader** [mhallsmoore/qstrader#106]
Sample data may need some cleanup and reorganization

I think it will be better to have sample data close to something that can be use in backtesting production.

I think we should split `data` directory into `data/bar` and `data/tick`

I also think that we should use "round" date range for data

SP500TR.csv for example is from 2010-01-04 to 2016-06-22
maybe we should only have data up to 2015-12-31.

A possible organization could be

```
data
    datasource1
        bar
            D
                2010
                    SP500TR.csv
                    another_ticker (to define).csv
                2011
                    SP500TR.csv
                    another_ticker (to define).csv
                2012
                    SP500TR.csv
                    another_ticker (to define).csv
                2013
                    SP500TR.csv
                    another_ticker (to define).csv
                2014
                    SP500TR.csv
                    another_ticker (to define).csv
                2015
                    SP500TR.csv
                    another_ticker (to define).csv
        tick
            2015
                2015-02
                    2015-02-01
                        MSFT.csv
                        AMZN.csv
                        GOOG.csv
```

`freq` string being
- `'D'` for daily
- `'H'` for hourly
- `'15T'` for 15 minutes
- ...

like in Pandas DateOffsets
see `pd.tseries.frequencies.to_offset('H').delta` and `?pd.date_range`
http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases

Moreover it will urge us to build price handler in a stream / iterate "fashion".

**Comment by mhallsmoore** [comment]
We need to be careful here as we should not be distributing data itself within the codebase. It will almost certainly be violating Terms Of Service of wherever it was taken from.

Instead we will need to have a post-install script that can download the data from Quandl/Yahoo or similar and then populate the directory structure as @femtotrader has suggested (which I do like a lot!).

**Comment by femtotrader** [comment]
We need some data for tests... so maybe just some "sample" data but with such a directory structure.

**Comment by mhallsmoore** [comment]
In that case we can generate it ourselves statistically. 

I don't mind having chunks of data in the codebase, it's just proprietary data from other sources that will be a problem. We can replace these data sources with our own fake "stock" prices and then use these in our tests.
