### ISSUE TITLE
Roadmap and Milestone Development

### ISSUE THREAD

**Issue by mhallsmoore** [mhallsmoore/qstrader#107]
Given the fact that QSTrader is now gaining more momentum (and a lot of new contributors), as well as becoming a more robust system, I feel it is necessary to start thinking about "official" roadmaps and developments carried out via milestones.

I appreciate that it will add a little extra communication overhead to the project and will be somewhat more "formal" but it will make it more attractive for both retail and institutional quants a like if there is a known versioning/feature roadmap that can be relied upon. In addition, new contributors will be able to know how and when their contributions will make it into the core codebase.

At this stage we've all been adding some brilliant features (certainly @ryankennedyio and @femtotrader have made great contributions!), but we've all been working on an ad-hoc basis, individually.

It's now time to start using a milestone approach (via the Github Milestones interface) and begin working towards a beta package that we'll all be happy to put into the PyPI repository.

Thoughts?

**Comment by femtotrader** [comment]
Transfer this project to a GitHub organization is something that could help.
see https://github.com/mhallsmoore/qstrader/issues/34

**Comment by nwillemse** [comment]
@mhallsmoore this will also help with who is working on what part of the application so that we don't overstep each other or do the same work twice.

**Comment by ryankennedyio** [comment]
Yep, agreed. 

I guess @nwillemse we should possibly have assigned tasks to make things more clear in that regard?

**Comment by nwillemse** [comment]
Yes I think that would be good to know who is working on which part of the app.
