### ISSUE TITLE
PortfolioHandler being aware of the backtest "time"

### ISSUE THREAD

**Issue by mhallsmoore** [mhallsmoore/qstrader#109]
I'm working on a small change to the interface today that will allow the PortfolioHandler (and PositionSizer/RiskManager) to be aware of the Backtest `cur_time` so that these modules can perform time-based actions, such as:
- Daily/Weekly/Monthly rebalancing - Very common in industry
- Seasonal risk adjustment
- "Closing out the book" in particular months (e.g. shutting down all trading in December if a fund has had a good year!

I'll put up a pull request when I'm done (possibly tomorrow) but if anybody has any architectural thoughts on this in the meantime, I'd be keen to hear them.

**Comment by nwillemse** [comment]
@mhallsmoore rebalancing is definitely something I am interested as well. Another thing to add in the same line of thought is for the backtester to have a start and end dates.  For instance in the mac_backtest example, it takes 200 days (bars) to "warmup" or "bars needed" before producing signals.  Thus we have 200 days of the same equity in the statistics class which I'm currently working on.  This will also allow us to run backtest on a specified period, like 2015-01-01 to 2015-12-31 regarding of how much data is available.

Nick

**Comment by mhallsmoore** [comment]
@nwillemse I had a quick go of modifying the way PortfolioHandler behaves, by allowing it access to the "current time" of the backtest. This is determined from the last market event received. In live trading we can just get the system time.

The MonthlyRebalancePositionSizer (or similar) then makes use of this current time to determine whether rebalancing should be occurring by ignoring all SuggestedOrder events unless they occur on the rebalance day in question. 

I'll eventually extend this to check what is already in the Portfolio and then only rebalance if new equities are needed, otherwise the orders are eliminated (and thus never executed).

**Comment by ryankennedyio** [comment]
Sounds good @mhallsmoore. 

Might allow us to clean up that "fix" in Compliance, where Compliance needs to know the "time" of the trade. A bit better if we're consistent through the system, where anything goes and gets `backtest.cur_time` if needed.

**Comment by ryankennedyio** [comment]
Also adding a suggestion that we only do `update_value()` every time `Backtest.cur_time` increases. This will take it out of the Backtest loop.

E.g. pretend we're doing minute bars of the SP500. Every minute, we perform `portfoliohandler.update_portfolio_value()` 500 times -- once for each instrument. 

Might as well only do this once at each step forward through time.
