### ISSUE TITLE
Enum34 dependency still needed?

### ISSUE THREAD

**Issue by subiol** [mhallsmoore/qstrader#112]
I believe enum34 dependency is not needed anymore.

I just started checking QStrader and when installing the dependencies everything went smooth, except enum34 is not compatible with python 3.5. After looking into it for a bit, I saw that Python 3.5 has now native enum that has also been backported to 3.x versions. I also checked the qstrader code and saw that [event.py](https://github.com/mhallsmoore/qstrader/blob/master/qstrader/event.py) does not use enum34 but the native python enum. So I run the buy and hold example without enum34 in my system and it did without problems.

So either enum34 is used in a part of the code that I have not hit, or enum34 was left by mistake in requirement.txt when the update to native python enum was done.

**Comment by mhallsmoore** [comment]
Hi subiol,

I think it is more likely the latter! I'll run a check over all the examples and remove it from the dependencies if necessary.

Mike.

**Comment by femtotrader** [comment]
enum34 is for Python 2.7 compat

**Comment by femtotrader** [comment]
https://pypi.python.org/pypi/enum34
Python 3.4 Enum backported to 3.3, 3.2, 3.1, 2.7, 2.6, 2.5, and 2.4

**Comment by subiol** [comment]
Ok, so enum34 is the backport. Is there a way to indicate that the package is not needed in python >3.4 in the requirement.txt file? It is confusing for new users when a dependency does not install. I do not know what is the standard way to handle this in python.

**Comment by mhallsmoore** [comment]
I've just looked this up on the pip docs:
https://pip.pypa.io/en/stable/reference/pip_install/#requirement-specifiers

It looks like we might be able to specify installing enum34 only for Python 2.7. 

What do you think @femtotrader?

**Comment by femtotrader** [comment]
https://github.com/mhallsmoore/qstrader/issues/118 might first be fixed

and after (as Python 3.3 won't be a supported version) we should put

    enum34>=1.1.6 ; python_version <= '2.7'

in https://github.com/mhallsmoore/qstrader/blob/master/requirements.txt#L21
