### ISSUE TITLE
Github/Slack Integration

### ISSUE THREAD

**Issue by mhallsmoore** [mhallsmoore/qstrader#117]
Hi all,

CC @ryankennedyio, @femtotrader, @nwillemse, @muke5hy... and others!

I've just carried out Github/Slack integration as per @ryankennedyio's suggestion. I couldn't think of a better place to put this, so have posted it here!

In order to participate in the Slack chat I will need to authorise an email address/account. If anybody would like to have access then please email me (mike@quantstart.com) your email address that you like to use for your account and I will send out invites.

I'm going to be out of the office for a while today, so there might be a bit of a delay in authorising your account(s), but I can definitely do it this evening!

Mike.

**Comment by femtotrader** [comment]
This issue should be closed

**Comment by mhallsmoore** [comment]
Agreed. I'm going to be making a standing post on the site about this, so future developers can just email me for an invite.
