### ISSUE TITLE
Interactive Brokers market data PriceHandler object

### ISSUE THREAD

**Issue by mhallsmoore** [mhallsmoore/qstrader#120]
This is a large chunk of work to create a PriceHandler object for dealing with market data received from Interactive Brokers.

It serves a few purposes:
- It will be the first proper integration (and testing) of QSTrader against IB, without the worry about committing capital to alpha versions of the software (i.e. no live trading)
- It will enable us to run some statistics on market data receipt latency for users around the world
- It will allow those who don't have IQFeed (or similar proprietary data source) to access "good" market data

The main features of such a system will include:
- A "streaming" price mechanism. The PriceHandler will open a connection to IB and stream market data prices, which will be converted into Events of the appropriate type. 
- We might need to store extra meta information for IB market events so will need some derived subclasses of Event.

Question:
- How will we deal with the price streaming system shutting off unexpectedly? We need to think about reconnections and effects on the trading system (which might be expecting a stream of market events, without interruption).
- Do we want to separate out the Streaming class from the PriceHandler class? We are likely to want to have more streaming price handlers (e.g. OANDA) in the future.
- Where will we store the config for individuals IB account details? We must make absolutely sure this never touches the codebase via accidental git commits (ENVVARS come to mind as the usual solution).

Thoughts?

**Comment by ryankennedyio** [comment]
Few extra points

- I think @femtotrader's big PR could form a nice base for this ? If anyone _needs_ to implement their own PriceHandlers (Bloomberg feed, etc), I'm sure they'll be able to figure it out quickly. I think the complexity is nicely 'tucked away' from the end user in that PR.
- We should use https://github.com/Komnomnomnom/swigibpy. This is exactly the same API as the C++ one offered by IB, so the IB documentation works perfectly.
- We must also think about how to mock these IB calls for our tests. Easy, boring, but easy to forget.

**Comment by femtotrader** [comment]
I'm working with IG
https://github.com/femtotrader/qstrader/tree/ig_price_handler
and I'm now able to display ticks through qstrader

**Comment by mhallsmoore** [comment]
That's nice - I can see us having multiple account IDs like this, although ENVVARs are certainly the way to go.

**Comment by femtotrader** [comment]
ENVVARs are the way to go to override some settings (can be necessary for security reason such as running on CI server, etc...)

**Comment by ryankennedyio** [comment]
One more thought to the list;

* In the case of dropout and multiple failures with some kind of backoff function, we should notify the user through Twilio or Email. This ExceptionHandler can/should be reused for IBExecutionHandler too.

**Comment by nwillemse** [comment]
@ryankennedyio another idea could be Slack integration and send trading messages via slack.  I'm doing it currently during the day to calculate signals prior to the close for trading.  It's surprisingly fast to deliver those messages.

**Comment by femtotrader** [comment]
We shouldn't add this kind of feature too deeply into qstrader code.
Maybe logging is enough and use a specific logging handler for this is enough

We can use 

- standard logging module https://docs.python.org/3/library/logging.html
- logbook http://logbook.readthedocs.io/

logbook come by default with a lot of handler (syslog, email, zeromq, redis, twitter...) http://logbook.readthedocs.io/en/stable/quickstart.html#handlers

I think a good idea will be to build our own handler(s)

[PushOver](https://pushover.net/) is also a nice API for real-time notifications on Android, iPhone, iPad, and Desktop (Pebble, Android Wear, and Apple watches, too!)
Some Python code
https://pushover.net/faq#library-python
https://bitbucket.org/jgoettsch/py-pushnotify/
https://github.com/wyattjoh/pushover/blob/master/pushover.py
http://chump.readthedocs.io/en/latest/
https://github.com/Thibauth/python-pushover
(and probably many other...)

**Comment by ryankennedyio** [comment]
Good point, logging is a better place for this. User notifications should be handled based on the Log 'importance' level.

**Comment by ryankennedyio** [comment]
I'll make a start on this, this evening.

@mhallsmoore could you please create a separate branch from Master for this ? That way we can all PR into the specific branch, and ensure Master stays in a fairly consistent state.

**Comment by mhallsmoore** [comment]
New branch has been created - https://github.com/mhallsmoore/qstrader/tree/ibpricehandler

**Comment by JP-MRPhys** [comment]
@ryankennedyio did you manage to make progress ? I have been playing with Blampe/IBPY please let me know if you would like to have look to assess if integration with qstrader is possible, I could email you in private as it is very basic ATM. However, I do think integration with qstrader should be relatively trivial once I have managed to look into design/philosophy of qstrader. 

I also think threading for simultaneous multiple order/portfolio monition/tracking might be a way forward, any thoughts ?

**Comment by ryankennedyio** [comment]
@JP-MRPhys I have made a start at:
https://github.com/mhallsmoore/qstrader/pull/133

Feel free to suggest/join in! I expect that branch will be worked on by a few people until it's ready.

We have discussed multithreading briefly and I think we're looking to just focus on getting a Beta ready which supports live trading on a few strategies concurrently. I agree that we will want to support multithreading though.

**Comment by femtotrader** [comment]
Beginning with release 9.73, a new Python API client is now included. After you install this beta release on your computer, you can find Python API components in the following locations:

Python API sample code – located in the samples/Python folder in your API installation directory (typically IB_973)
Python source code – located in the source/pythonclient folder in your API installation directory

Source
https://www.interactivebrokers.co.uk/en/index.php?f=5061&ns=T&nhf=T
https://interactivebrokers.github.io/tws-api/#gsc.tab=0
https://github.com/blampe/IbPy

**Comment by mhallsmoore** [comment]
It's interesting that the IB API requires Python >= 3.1.

This would obviously have implications for QSTrader being a Python2.7.x and Python 3.x.x compatible library.

Given the fact that Python is gradually moving to Python3, I think we should consider making QSTrader a Python 3.x.x only library.

Thoughts?

**Comment by lionelyoung** [comment]
Pandas and numpy also moving to Python3 so it's a good idea

**Comment by SteffenNa** [comment]
You might want to consider using [ib_insync](https://github.com/erdewit/ib_insync) which is a well supported and documented high level wrapper for the Python IB API. It handles all the painful stuff
