### ISSUE TITLE
PriceHandler should have base `get_last_price()`

### ISSUE THREAD

**Issue by ryankennedyio** [mhallsmoore/qstrader#125]
In order for other components to get the last price without knowing what type of Events the price handler emits (tick, bar, etc), there should be a single `get_last_price()` function that is shared by all PriceHandler implementations.

Will help @nwillemse with his tearsheet statistics class. 
I'll fix this issue this evening.

**Comment by femtotrader** [comment]
Hi @ryankennedyio ,

I think it will be better to do this after merging
https://github.com/mhallsmoore/qstrader/pull/103/

**Comment by femtotrader** [comment]
An other idea... `get_best_bid_ask` returns bid and ask and `get_last_close` returns close price

both methods only need ticker

I think both method should only return one price and so we need to know if we are looking for bid or ask price and so order (or a lest order action) also need to be passed to this `get_last_price` method

**Comment by ryankennedyio** [comment]
Good point @femtotrader . Will wait on merge.

**Comment by femtotrader** [comment]
Thanks @ryankennedyio because it's a pain to manage merge conflicts!

**Comment by ryankennedyio** [comment]
Note to fix https://github.com/mhallsmoore/qstrader/issues/104 at the same time.

Am spending this week getting cosy with swigibpy and IB API again, so if anyone wants to jump in on this in the meantime that'd be great!

**Comment by mhallsmoore** [comment]
Have you seen the posts by Rob Carver?
http://qoppac.blogspot.co.uk/2014/03/using-swigibpy-so-that-python-will-play.html

**Comment by ryankennedyio** [comment]
Yeah! Was using for some inspiration :) Very good series of posts he has on it.

**Comment by mhallsmoore** [comment]
@ryankennedyio - Can we close this given the merge of #103?

**Comment by ryankennedyio** [comment]
@mhallsmoore implemented in https://github.com/mhallsmoore/qstrader/blob/master/qstrader/price_handler/base.py#L98, so yep ready to close.

**Comment by mhallsmoore** [comment]
Great.
