### ISSUE TITLE
Fix the import of "queue" and "Queue" for Python 2.7.x and 3.5.x compatibility

### ISSUE THREAD

**Issue by mhallsmoore** [mhallsmoore/qstrader#13]
This simply requires a try...except block, for all necessary files importing the queue library, as in QSForex.

**Comment by cb4gusto22** [comment]
Hello, I'm a bit new to Python and github but I am interested in the project and want to help out! I believe I've made the fix, but am having trouble with "git push" (i.e. permission denied). Do I need to be given permission first or should I fork the original, push to it, then create a pull request? Thank you

**Comment by cb4gusto22** [comment]
OK, after playing around I believe it is the latter. I'll initiate a pull request upon your confirmation. Thanks!

**Comment by mhallsmoore** [comment]
Indeed, it should look like this:

```
try:
    import Queue as queue
except ImportError:
    import queue
import time
```

Feel free to submit a pull request as well! Thanks for fixing it.

**Comment by mhallsmoore** [comment]
This has now been merged into master.
