### ISSUE TITLE
Pandas_datareader dependancy merging

### ISSUE THREAD

**Issue by ryankennedyio** [mhallsmoore/qstrader#131]
https://pypi.python.org/pypi/pandas-datareader

implies that `pandas_datareader` is now part of Pandas 0.18.1. I've just updated Pandas version, so we should get rid of this extra dependancy if possible.

**Comment by femtotrader** [comment]
Sorry @ryankennedyio but I think maybe we weren't clear enough

[data.py](https://github.com/pydata/pandas/blob/master/pandas/io/data.py) was part of Pandas and is now deprecated in favor of [pandas-datareader](https://github.com/pydata/pandas-datareader/)

**Comment by femtotrader** [comment]
My opinion about pandas-datareader and qstrader is that in a quite close future we should have raw data inside qstrader repository (in nicely organised directories see https://github.com/mhallsmoore/qstrader/issues/106 ) instead of relying to external data source for testing purpose.

**Comment by ryankennedyio** [comment]
Fair enough, I will close :)

TBH I can't see including data in the repo as a good idea -- with the exception of the bare minimum needed for testing (so maybe daily FANG and a generated day of ticks).

Otherwise we add a load of questions like how should the data remain updated, what if the user doesn't need that data, what if the user uses another data source, what if the user doesn't want CSVs, etc etc etc.

I think we should be pretty data agnostic. Provide the bare bones, allow users to do something very simple to start with, and add their own database & connection through pricehandler if they want something complex. E.g. we should think about users on KDB, Bloomberg, Reuters, custom ticker plant (e.g. Nanex data), etc etc.
