### ISSUE TITLE
Could qstrader add a benchmark plot, sharpe ratio, MaxDrawdown? 

### ISSUE THREAD

**Issue by easytrader** [mhallsmoore/qstrader#140]
![multi_rsi](https://cloud.githubusercontent.com/assets/15394723/18809554/e8cda484-82b0-11e6-8244-fb0440682f9b.png)

Thank you.

**Comment by ryankennedyio** [comment]
@easytrader this and a few more neat things are available in: the `Tearsheet` statistics class.

Looks a little something like;
![screen shot 2016-09-25 at 10 22 22 am](https://cloud.githubusercontent.com/assets/11158006/18813102/cf113fae-832a-11e6-9526-7e6659717268.png)

**Comment by mhallsmoore** [comment]
Thanks for commenting @ryankennedyio . I'll close this unless there are any other specific features you think might be useful, @easytrader?
