### ISSUE TITLE
Tearsheet Statistics needs time-scale

### ISSUE THREAD

**Issue by DirkFR** [mhallsmoore/qstrader#141]
Hi,

The tearsheet should have an axis label and ticks (years) for the "Cumulative Returns" and "Drawdown %" charts. 
That would make reading the charts much easier.

Thanks in advance!
Dirk

**Comment by femtotrader** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/5049737/18985924/ab6369be-86fa-11e6-8fb1-4af9c06c2a49.png)

**Comment by DirkFR** [comment]
Thanks - maybe I should have said this differently: 
In the top 2 charts, I don't see the days/dates/months.
Example: The drawdown starts in which month according to the 2nd chart from the top?
Or am I looking at this all wrong?

**Comment by ryankennedyio** [comment]
You're right @DirkFR , those two charts should have it.
