### ISSUE TITLE
cannot install qstrader 

### ISSUE THREAD

**Issue by linus791025** [mhallsmoore/qstrader#170]
after typing this cmd in terminal:

"pip install git+https://github.com/mhallsmoore/qstrader.git"

i get this error:
any help appreciated.

"Found existing installation: numpy 1.6.2
    DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.6.2:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy-1.6.2-py2.7.egg-info'
"

**Comment by mhallsmoore** [comment]
Hi Linus,

I believe the issue might be due to how NumPy is installed system-wide. I presume you are using this on Mac OS X? 

Have you tried creating a separate virtual environment, perhaps with Continuum Analytics' Anaconda?
https://www.continuum.io/downloads

This will help keep your QSTrader environment "cleaner" from the system Python.

Mike.

**Comment by linus791025** [comment]
Hi Mike,

Thank you for your quick response! I am going to try it.

Thank you!

Linus

**Comment by linus791025** [comment]
Hi Mike,

I have already installed Anaconda in my Mac but not in a virtual environment. It is still not available to install qstrader.

Is it possible to install qstrader package in Mac without creating another virtual environment?

Thank you!

Linus

**Comment by linus791025** [comment]
Hi Mike,

I have already solved this issue by creating another virtual environment in Anaconda and installed qstrader successfully! (sorry, this is my first time using Python)

Thank you!

Linus

**Comment by mhallsmoore** [comment]
Hi Linus,

No problem - let me know if you have any further issues.

Mike.
