### ISSUE TITLE
IB Python API

### ISSUE THREAD

**Issue by ryankennedyio** [mhallsmoore/qstrader#171]
So Interactive Brokers now offers a native Python API:
https://www.interactivebrokers.com.au/en/index.php?f=5061&ns=T&nhf=T

I have a stack of code written for an IBPriceHandler, but nothing yet for IBExecutionHandler. Shall we swap from SWIG based implementation to *full* python?

Getting off of SWIG means one less dependancy for the testing suite (also the swig implementation needs to be manually installed because of version differences between github & pypi).

PS sorry for disappearing for a while there! Had some burnout to fend off

**Comment by canada4663** [comment]
FWIW - I also spent quite a bit of time playing with the SWIG version.  There are some challenges in copying and using the underlying SWIG objects passed back and forth (Contract, Order, ComboLegs, etc).  I think as you get deeper in using the IB API for trading, getting account data, etc you will benefit from having native python API.

I spent an hour or so going through the code, and it seems they've used the same approach as the other versions.  Not 100% feature complete on version 973 yet, but cursory glance shows all the features on the stable release are available.

If I get a chance to play with it here in near future, will share.  I am glad they have a native python version now.

**Comment by ryankennedyio** [comment]
Will be very interesting for options contracts, as you allude to.

Seems like it might be best to go that way then!

**Comment by mhallsmoore** [comment]
Hi Ryan, good to hear from you again!

I agree with you in that the native client is clearly the way forward. Not having an extra dependency (specifically regarding the version differences you mention above) would also be beneficial.

I made some suggestions regarding the implementation on the Slack #general channel this morning - let me know what you think.

Mike.

**Comment by ryankennedyio** [comment]
Closing as work has been started on a pull request
