### ISSUE TITLE
Tearsheet:  Distribution of Returns (per trade)?

### ISSUE THREAD

**Issue by ryankennedyio** [mhallsmoore/qstrader#173]
Just throwing it out there as something that people may find useful. Also outputting a CSV of each trade, & each trade's return, likely in the compliance module.

May be dangerous to rely on heavily as you'll end up doing almost explicit overfitting if you pay too much attention to it during backtests -- but that's what in/out of sample & other backtesting best practice is for ... 

Happy to implement if others would find value in it.

**Comment by AttilaTheCoder** [comment]
I just started migrating a strategy from my own algo framework and this would be very helpful to test/verify easily. I would argue not only helpful but a requirement to use the platform and self created strategies with confidence.

**Comment by ryankennedyio** [comment]
Sure thing. I'll likely do a daily distribution of returns, and a distribution of 'trade' returns as well, as I think they both provide value in a different way.
