### ISSUE TITLE
Calculation Error in Sortino Ratio 

### ISSUE THREAD

**Issue by gk6294** [mhallsmoore/qstrader#179]
Reference to: https://www.quantstart.com/articles/kalman-filter-based-pairs-trading-strategy-in-qstrader
For Python 3.6, issue occurs in calculating the Sortino Ratio as below:
Suggested modification - Use np.std(returns[returns._values_ < 0])

**Comment by lionelyoung** [comment]
I found an issue in Pandas with Python 3.6.0 that raises this error
Python 3.5.2 works
