### ISSUE TITLE
Feature/discussion: Simulated financial data with statistical properties

### ISSUE THREAD

**Issue by mhallsmoore** [mhallsmoore/qstrader#18]
I'm likely to be creating a module that will provide simulation of financial time series data in order to test certain statistical machine learning models.

The main reasons for this are:
- The data can be simulated on any timescale (e.g. tick/quote through to monthly)
- Correlated data sources can be generated (e.g. via this method: https://www.quantstart.com/articles/Generating-Correlated-Asset-Paths-in-C-via-Monte-Carlo)
- The data can be simulated with abrupt or gradual changes in simulation parameters to represent "regime change"
- Varying degrees of noise can be added to the data in order to test effectiveness of underlying parameter reconstruction

It should provide a good test-bed for statistical machine learning techniques prior to the usage of real-world financial data, which should help avoid overfitting problems.

Please let me know your thoughts!

**Comment by hgeorgako** [comment]
Another interesting simulation approach would be some sort of zero-intelligence model.  This will emulate the actual return profile better than  providing a rigid Brownian motion model.  You either make basic assumptions about the limit order arrival rate, cancellation rate and market order rate, or calibrate those parameters off of sample data.  Once you have those values, you can simulate to your hearts content.

**Comment by mhallsmoore** [comment]
That is certainly an interesting idea! Although I hadn't really considered carrying out a full limit order book simulation. I do like your idea of a "middle ground" though.
