### ISSUE TITLE
Adj Close and pct rtrn 

### ISSUE THREAD

**Issue by alex-muci** [mhallsmoore/qstrader#182]
A couple of financial suggestions:

- Better an Adjusted Close than the simple close to be called in '_update_portfolio' in 'qstrader/qstrader/portfolio.py'
I was running a backtesting on a VIX ETF (notoriously famous for splits) and
got the wrong results because close prices used rather than adj close ones (which are available with Yahoo)

- pct = ((self.equity[-1] - self.equity[-2]) / self.equity[-1]) * 100
in qstrader/qstrader/statistics/simple.py
A more natural definition is (new - old) / old, i.e. denominator should be 'self.equity[-2]'

**Comment by ryankennedyio** [comment]
Good points. We should probably be using log returns actually.
