### ISSUE TITLE
"from munch  import munchify, unmunchify"

### ISSUE THREAD

**Issue by MountainCountry** [mhallsmoore/qstrader#185]
I keep getting this error in the 'settings.py' file.  Can't locate 'munch' module.

Thoughts?

**Comment by nwillemse** [comment]
The python munch module is missing.  Do the following to install it:

Python2: `pip install munch`
Python3: `pip3 install munch`

or to install all the requirements:
`pip install -r <qstrader directory>/requirements.txt`
