### ISSUE TITLE
Wrong command in README.md

### ISSUE THREAD

**Issue by easytrader** [mhallsmoore/qstrader#187]
![21345](https://cloud.githubusercontent.com/assets/15394723/23550878/538a7a34-004e-11e7-86a6-c909d6442c15.png)
It should be modified:
wget https://raw.githubusercontent.com/mhallsmoore/qstrader/master/data/SPY.csv

**Comment by gcmartinelli** [comment]
I think this is linked to https://github.com/mhallsmoore/qstrader/issues/193

**Comment by mhallsmoore** [comment]
I believe this has now been fixed.
