### ISSUE TITLE
Backtesting intraday data has overnight (space) gaps in equity curve

### ISSUE THREAD

**Issue by ryankennedyio** [mhallsmoore/qstrader#188]
As pictured;

![screen shot 2017-03-08 at 11 46 43 am](https://cloud.githubusercontent.com/assets/11158006/23684949/be1ec8be-03f5-11e7-9931-7c310f85050b.png)

**Comment by JamesKBowler** [comment]
Does the data your using have gaps?

**Comment by ryankennedyio** [comment]
Oh right, is it something to do with the `hasGaps` that IB's API returns with historical data?

This is just grabbing the last 5 days of 1-minute data for a particular stock
