### ISSUE TITLE
import error no module tkinter

### ISSUE THREAD

**Issue by balldekdee** [mhallsmoore/qstrader#189]
When I run python buy_and_hold_strategy.py   I ran into the problem
ImportError: No module named '_tkinter'
and could not run the backtest 
please help

**Comment by JamesKBowler** [comment]
Is the module installed?
Did you install  with/without sudo x....?

http://tkinter.unpythonic.net/wiki/How_to_install_Tkinter

**Comment by mhallsmoore** [comment]
Are you running this on Windows, Mac or Linux?
