### ISSUE TITLE
cannot found the DisplayStrategy routine

### ISSUE THREAD

**Issue by zxweed** [mhallsmoore/qstrader#191]
After successful installation of QSTrader I cannot run any examples that imports DisplayStrategy:
```
from qstrader.strategy import DisplayStrategy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-d4341002266b> in <module>()
----> 1 from qstrader.strategy import DisplayStrategy

ImportError: cannot import name 'DisplayStrategy'
```

I have not found any occurence of "DisplayStrategy" substring in the master repo, but it was found in some other branches..

**Comment by femtotrader** [comment]
It have been removed by https://github.com/mhallsmoore/qstrader/pull/177
Pinging @mhallsmoore
