### ISSUE TITLE
Links to data and example at the website (https://www.quantstart.com/qstrader) are broken

### ISSUE THREAD

**Issue by gcmartinelli** [mhallsmoore/qstrader#193]
There are two broken links mentioned on the installation instructions at [https://www.quantstart.com/qstrader](https://www.quantstart.com/qstrader):

- https://raw.githubusercontent.com/mhallsmoore/qstrader/master/data/SP500TR.csv

- https://raw.githubusercontent.$ com/mhallsmoore/qstrader/master/examples/buy_and_hold_backtest.py

**Comment by uiopwang** [comment]
Try this.
``` shell
 cd ~/data
 wget https://raw.githubusercontent.com/mhallsmoore/qstrader/master/data/SPY.csv
 cd ~/qstrader/examples
 wget https://raw.githubusercontent.com/mhallsmoore/qstrader/master/examples/buy_and_hold_backtest.py
```
