### ISSUE TITLE
Read me file missing

### ISSUE THREAD

**Issue by bicepjai** [mhallsmoore/qstrader#2]
could you add a read me file that might help a tyro ?

**Comment by mhallsmoore** [comment]
Hi bicepjal,

I've just added an _interim_ README.md to the project, with some basic explanation. I've still got to work on producing full installation instructions, however.

Mike.

**Comment by mhallsmoore** [comment]
A new README.md file with installation instructions has been added as of a recent version, so I'm going to close this issue.
