### ISSUE TITLE
Multiple tickers, with price values in one market event

### ISSUE THREAD

**Issue by mhallsmoore** [mhallsmoore/qstrader#200]
A common pattern that I've found in carrying out strategy development, particularly with equity portfolios involving many tickers, is that the AbstractStrategy-derived strategy class must keep a tally of all current prices of each ticker it is interested in. This is particularly problematic for equity portfolios consisting of 30+ tickers.

In particular, for some of my strategies, it must wait to carry out any strategy logic until all ticker closing prices for a particular day have arrived. This means the receipt of N MarketEvent objects. 

Rather than sending each individual ticker in a separate market event it might be better to instead create a DailyMarketEvent object (or similar) that provides bar information for all interested tickers in one go, thus reducing the need for boilerplate code living within the strategy class itself that keeps track of prices.

Let me know what you think of this and I'll code up a test to see how it works in practice.

**Comment by ryankennedyio** [comment]
I think the computational complexity is equivalent either way (i.e. same amount of 'work' must be done), it's just a question of whether the logic should be in the strategy or the event loop.

One thing I know that would help us out with the event loop speed is ensuring that `update_portfolio()` and `statistics.update()` only get called _at the next timestep_, rather than at every new bar. 

I think there might be an opportunity to do two birds with one stone there.

**Comment by femtotrader** [comment]
A priority queue may help https://github.com/femtotrader/femtotrading/blob/master/femtotrading/priority_queue.py

**Comment by enriqueromualdez** [comment]
Any developments on this enhancement? Would be great to run tests on multiple tickers..

**Comment by enriqueromualdez** [comment]
Hey all, 

Attempting to figure this out now. I am a bit lost on the best approach as so far, what I've come up with might not exactly be the most efficient way of doing things. Is it possible to combine`BarEvent`s into a single `BarEvent`? Maybe as a list which contains` BarEvent`s that share the same timestamp that can then be iterated over by `_run_sessions()`? 

The problem I see with this approach is of course the fact that _run_sessions() will prioritize whichever Ticker comes up first from the `BarEvent` list. 

Any other ideas? Multi-threading makes sense, but that's beyond me... Haha.
