### ISSUE TITLE
Installation error git not found.

### ISSUE THREAD

**Issue by ANURAGMN** [mhallsmoore/qstrader#201]
when I gave this for installation:
  cmdprmpt>pip install git+https://github.com/mhallsmoore/qstrader.git
Collecting git+https://github.com/mhallsmoore/qstrader.git
  Cloning https://github.com/mhallsmoore/qstrader.git to c:\users\murali\appdata
\local\temp\pip-vr7qb6jd-build
  Error [WinError 2] The system cannot find the file specified while executing 
command git clone -q https://github.com/mhallsmoore/qstrader.git C:\Users\murali\
AppData\Local\Temp\pip-vr7qb6jd-build
Cannot find command 'git'

also when i tried:
   cmdprmt>git clone https://github.com/hallsmoore/qstrader.git
'git' is not recognized as an internal or external command,
operable program or batch file.

Also, dono about env.

**Comment by hkopp** [comment]
To me it looks like you do not have git installed, but I am no windows expert.
Also in the second try you are missing the 'm' in the URL from mhallsmoore.

**Comment by mindlessbrain** [comment]
> Cannot find command 'git'

@ANURAGMN on windows, you can download git from [here](https://git-scm.com/download/win), or install it using [conda](https://anaconda.org/anaconda/git) (this I never tested). It should solve your first attempt for installing qstrader.

> 'git' is not recognized as an internal or external command,
operable program or batch file.

If you have git installed already, then you should use the git bash (from the start menu), and you should be able to clone this repository.

> Also, dono about env.

You are using [anaconda](https://www.continuum.io/downloads) on windows, right?
If so, you can use virtual environments by following [their documentation](https://conda.io/docs/using/envs.html).
You can also use [python's](https://docs.python.org/3/library/venv.html) virtual environments. (this one is harder to configure, but I think it works better than conda's).

**Comment by mhallsmoore** [comment]
Hi @ANURAGMN, @hkopp and @mindlessbrain,

I've now released QSTrader to PyPI to allow straightforward installation via ``pip install qstrader``. This should fix the above issue since it does not require Git anymore.

Installation into an Anaconda 3.7 environment should work on Windows. However, if it does not, please let me know and I will re-open this issue.

Kind regards,

Mike.
