### ISSUE TITLE
FXCM Data and intergration with QSTrader

### ISSUE THREAD

**Issue by JamesKBowler** [mhallsmoore/qstrader#202]
Hi team,

Just thought I would pop in and say, I have written a python program to download all of FXCM's data, both historical and live.

My next move is to integrate QSTrader with FXCMs API.

You can find fxcmminer at the link below.... be nice its my first one!
https://github.com/JamesKBowler/fxcmminer

Thank-you

Regards

James

PS.. sorry for spamming your repo Michael

**Comment by mhallsmoore** [comment]
Hi James,

No problem at all! This looks great.

Let us know if you want any integration help. If you want an invite to the Slack, just email me at "mike@quantstart.com" and I'll send it out.

Cheers,

Mike.

**Comment by JamesKBowler** [comment]
Hi Mike, sure please invite me over! I have sent you an email 
Thanks
James

**Comment by enriqueromualdez** [comment]
HI @JamesKBowler and @mhallsmoore,

Has there been any update on Forex integration? I've started working on combining QSForex with QSTrader, but I'm a bit unsure as to the best approach for doing this.

**Comment by JamesKBowler** [comment]
Will come back to this
