### ISSUE TITLE
Tearsheet Trade Count incorrect?

### ISSUE THREAD

**Issue by enriqueromualdez** [mhallsmoore/qstrader#208]
I attempted to create a FractionalPositionSizer to replace the FixedPositionSizer for backtesting with moving_average_cross_backtest.py. 

The output on the terminal for Longs and Shorts seems to be correct. It also coincides with the tradelog csv output. But for some reason, the tearsheet shows the Trade Count to be a totally different number?

e.x. 
Travelog.csv = 34 trades
Tearsheet = 9 trades

When I switch back to FixedPositionSizer, the tearsheet trade count is correct. So I'm guessing it has something to do with my code?

Here's my code for FractionalPositionSizer (Almost entirely based on the code from rebalance.py):

from math import floor
from .base import AbstractPositionSizer
from qstrader.price_parser import PriceParser

class FractionalPositionSizer(AbstractPositionSizer):
    def __init__(self, default_fraction=0.19):
        self.default_fraction = default_fraction

    def size_order(self, portfolio, initial_order):
        """
        This FractionalPositionSizer object simply modifies
        the quantitiy to be 5 percent of AUM for every
        share transacted.
        """
        ticker = initial_order.ticker
        weight = self.default_fraction
        # Determine total portfolio value, work out dollar weight
        # and finally determine integer quantity of shares to purchase
        price = portfolio.price_handler.tickers[ticker]["adj_close"]
        price = PriceParser.display(price)
        equity = PriceParser.display(portfolio.equity)
        dollar_weight = weight * equity
        weighted_quantity = int(floor(dollar_weight / price))
        initial_order.quantity = weighted_quantity
        return initial_order

 @mhallsmoore @femtotrader

**Comment by nwillemse** [comment]
@enriqueromualdez the `tearsheet` uses the number of `positions` for number of trades.  I guess it's confusing because it's called Number of Trades instead of number of Positions.  Maybe we need both on the `tearsheet`?  Especially in rebalancing, you make a lot of trades, but take only a very few positions...

**Comment by enriqueromualdez** [comment]
@nwillemse Interesting.. I'm still a bit confused though. My tradelog.csv output is actually 69, so I figured the tearsheet output of 34 was simply: 69 / 2 (BOT/SLD) = 34. I'm guessing this means 34 "round trips" correct?

With that being said, does that mean there's something wrong with my FractionalPositionSizer script then? 

I'll keep that in mind though, I'll see if I can make some adjustments in the tearsheet calculation to reflect trades instead.

**Comment by nwillemse** [comment]
Yes it should be 34. When you open a position and then close the position, that is 2 trades, but 1 position.  So it all depends on your trade logic. If you open 1 position, then add to it, then remove some shares, then close the position, it is still just 1 position (on `tearsheet`) but it's 4 actual trades.  I like to count the positions, but when I create a rebalancing portfolio, then I would like to know how many trades.  We should see if we can rename trades to positions and add trades to `tearsheet`.

**Comment by enriqueromualdez** [comment]
Ah that makes total sense.. I guess there must be something up with my "trades" not counting as "positions." Great idea for adding trades to the tearsheet as well. Should be easy enough to add that in. Cheers!

**Comment by enriqueromualdez** [comment]
Hi again @nwillemse,

I've spent the last couple of days trying to figure out why my "trades" are still not coming through as "positions".. Would you happen to have any ideas? I just can't seem to understand how the trade logic has changed due to my FractionalPositionSizer's function is to provide a fractional order.. No different than the FixedPositionSizer's default quantity of 100.

**Comment by nwillemse** [comment]
hi @enriqueromualdez 

Is it working when you run your strategy with the default FixedPositionSizer?

Check your sizes on both ends.  If you are long 100 shares, when you have to sold, does it sell 100?  That closes the `position` and counts as 1 "trades" on the `tearsheet`. However if you go long 100 then sell 90 then go long 130 and then sell 140, this will finally close the position for only 1 "trade".

**Comment by enriqueromualdez** [comment]
Hi @nwillemse, thanks for the response.

It works perfectly fine with the default settings. I actually was running it with my custom MySQLDataHandler as well, and the numbers matched up, so it wasn't that as well.

But the position size on both ends makes perfect sense! Wow, I for some reason never thought about that... Because the size does change due to my unrealized_pnl and realised_pnl increasing, so the trade sizes are usually higher or lower than the initial purchase.. I think that's definitely the issue here.

But with that being said, does that mean I need to change the definition of a closed "position" within portfolio.py? If so, I'm guessing this part of portfolio.py needs to be changed eh? Because I don't think it's appending any closed positions because of exactly what you explained with the changing share count.

```
if self.positions[ticker].quantity == 0:
                closed = self.positions.pop(ticker)
                self.realised_pnl += closed.realised_pnl
                self.closed_positions.append(closed)

```

**Comment by nwillemse** [comment]
I used fractional as well.  However, in my local copy the way I implemented it was to add a new `signal` type event call EXIT.  Then the `portfolio_handle`r needs to be updated in `create_order_from_signal` to check for EXIT signal and set the quantity for SuggestedOrder equal to the quantity of the current position.

Portfolio closed positions doesn't need to change. it's doing what its suppose to go, counting closed positions.  a position is closed once the net quantity reaches 0.  However, something to think about is what about SAR positions (stop-and-reverse)...So buy 100 and sell 200 should actually close the 100 position and open up another short 100 position.  I don't think it's currently being handled...

I hacked it together in a local copy here: https://github.com/nwillemse/nctrader/blob/master/nctrader/portfolio_handler.py

**Comment by enriqueromualdez** [comment]
Wow, I can't thank you enough mate. I never thought to add another signal.. I tell you, two days of trying to figure this out is a little mind bending. But the logic makes perfect sense now. 

In regards to SAR positions and based on your example, wouldn't the reversal simply count as a new entry signal on the short side? Therefore, the initial 100 long would be closed and the 100 short would be opened? Forgive me if I'm not on point with the logic here...

**Comment by nwillemse** [comment]
Yes, that's how I currently handle it.  Close current position issuing a EXIT signal, and then submit a entry signal.  I don't remember how `qstrader` handle's the case where you are long 100 and selling 110.  It should just close the position?  Or like in IB it actually creates a short position of 10 shares...

This brings up the next point :). I had to create a priority queue for the events, because i need to process EXIT signals before ENTRY signals in order to get the cash available for the next trade position sizing to be correct...

**Comment by enriqueromualdez** [comment]
Ah, well I haven't tried this out yet with IB, but does the trade logic change? Or does it match up with IB?

Also, I've had the chance to go through your code. You managed to figure out quite a bit! I do have another question though, it seems as if our FractionalPositionSizer script is vastly different. Do you think my current build will suffice with the "XIT" logic you've added into your modules? 

At the moment, I can't seem to figure out exactly where to put the signal_event.action == 'XIT' to trigger a full liquidation. Should it be within the strategy object itself? Or should the script just automatically know via the prioritization you've coded in that an "XIT" queue is always before an "BOT" queue?

Once again, I appreciate all the help man. It's great to see how far someone else has come. Lots of work to do on my end!

**Comment by nwillemse** [comment]
hi @enriqueromualdez 

In your strategy when you calculate signals, you create and put on the queue a `SignalEvent` with type XIT.  Then if you look at my portfolio_handler class, you will see where i'm checking for the XIT signal.  Just before it creates the SuggestedOrder it checks for the signal type and then find the open position num shares and that's the suggested order:

https://github.com/nwillemse/nctrader/blob/master/nctrader/portfolio_handler.py#L49

Yeah my FixedPositionSizer is a little more complicated: 

1. I needed to add a quick fix to trade futures.
2. I needed to add code to scale into a position `n` number of times.  The `_unit_shares()` does this calculation.
3. Then i have a `strength/dvar` variable which allows me to control how much of available equity to use.  This changes for 0 to 2 since I'm in a margin account and do leverage.  I got DVaR from there: https://cssanalytics.wordpress.com/2010/02/04/introduction-to-d-var-position-sizing-part-1/

My code is a bit messy and the tests don't really work.  I need to quickly pull this together so that I can backtest my system and compare it with my actual live trading results.

**Comment by enriqueromualdez** [comment]
I was able to sort the portfolio_handler class out, I guess I'm just having issues with when to actually calculate the XIT. I'm doing this within `calculate_signals` in the moving_average_cross_backtest.py file. I'll take another crack at it. Thanks again man.

And I know of VaR, but I never knew there was a position sizing technique for it! Interesting. I was hoping to try and implement Kelly Criterion once the whole fractional thing is sorted out. I'll keep you posted on the progress.. Cheers mate!

**Comment by enriqueromualdez** [comment]
@nwillemse 

After four days of trial and error, I finally got it to work! I can't believe how simple the solution was. Can't thank you enough for you help mate. On to the next module!
