### ISSUE TITLE
Tearsheet figure is shown for less than a second, and then immediately disappears

### ISSUE THREAD

**Issue by penalvch** [mhallsmoore/qstrader#211]
What is expected to happen is when using Windows 10 to run buy_and_hold_backtest.py noted in https://www.quantstart.com/qstrader the tearsheet figure created is shown, and stays visible for review.

What happens instead is the backtest runs in Anaconda Prompt:
```
python buy_and_hold_backtest.py
Running Backtest...
---------------------------------
Backtest complete.
Sharpe Ratio: 0.25
Max Drawdown: 79.59%

(qstrader) c:\Anaconda3\envs\qstrader\examples>
```

but the figure window is created for less than a second, and then immediately disappears. Please see debug log:
[debug.txt](https://github.com/mhallsmoore/qstrader/files/1081826/debug.txt)

WORKAROUND: Edit file C:\Anaconda3\envs\qstrader\Lib\site-packages\qstrader\statistics\tearsheet.py and change:
plt.show(block=False)

to:
plt.show()

**Environment Setup**

Windows 10 64-bit

Install Git:
https://github.com/git-for-windows/git/releases/download/v2.13.1.windows.1/Git-2.13.1-64-bit.exe

As per https://www.quantstart.com/knowledgebase/qstrader/installation/compatibility-issues-with-python-36x-pandas-and-qstrader install Anaconda via:
https://repo.continuum.io/archive/Anaconda3-4.2.0-Windows-x86_64.exe

_Execute in Anaconda Prompt:_
```
conda create --name qstrader
activate qstrader
conda install scipy==0.17.0
conda install wget
pip install git+https://github.com/mhallsmoore/qstrader.git
pip install -r https://raw.githubusercontent.com/mhallsmoore/qstrader/master/requirements.txt
```

Edit file:
C:\Anaconda3\envs\qstrader\Lib\site-packages\qstrader\settings.py

and change:
DEFAULT_CONFIG_FILENAME = '~qstrader.yml'

to:
DEFAULT_CONFIG_FILENAME = 'qstrader.yml'

Create blank qstrader.yml in:
C:\Anaconda3\envs\qstrader\examples\

Edit qstrader.yml and add:
CSV_DATA_DIR: C:\data
OUTPUT_DIR: C:\out

_Execute in Anaconda Prompt:_
```
mkdir c:\data
cd /d c:\data
python -m wget https://raw.githubusercontent.com/mhallsmoore/qstrader/master/data/SPY.csv
cd /d c:\Anaconda3\envs\qstrader\
mkdir examples
cd examples
python -m wget https://raw.githubusercontent.com/mhallsmoore/qstrader/master/examples/buy_and_hold_backtest.py
python buy_and_hold_backtest.py
```

```
conda list
# packages in environment at C:\Anaconda3\envs\qstrader:
#
backports.shutil-get-terminal-size 1.0.0                     <pip>
bleach                    2.0.0                     <pip>
certifi                   2017.4.17                 <pip>
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
cycler                    0.10.0                    <pip>
decorator                 4.0.9                     <pip>
entrypoints               0.2.3                     <pip>
enum34                    1.1.6                     <pip>
html5lib                  0.999999999               <pip>
idna                      2.5                       <pip>
ipykernel                 4.6.1                     <pip>
ipython                   4.2.0                     <pip>
ipython-genutils          0.1.0                     <pip>
ipywidgets                5.1.5                     <pip>
Jinja2                    2.9.6                     <pip>
jsonschema                2.6.0                     <pip>
jupyter-client            5.0.1                     <pip>
jupyter-core              4.3.0                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                1.5.3                     <pip>
mistune                   0.7.4                     <pip>
mkl                       11.3.3                        1
multipledispatch          0.4.9                     <pip>
munch                     2.1.1                     <pip>
nbconvert                 5.2.1                     <pip>
nbformat                  4.3.0                     <pip>
notebook                  5.0.0                     <pip>
numpy                     1.11.2                   py35_0
numpy                     1.10.4                    <pip>
pandas                    0.18.1                    <pip>
pandas-datareader         0.2.1                     <pip>
pandocfilters             1.4.1                     <pip>
path.py                   8.1.2                     <pip>
pexpect                   4.0.1                     <pip>
pickleshare               0.6                       <pip>
pip                       9.0.1                    py35_1
ptyprocess                0.5.1                     <pip>
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.0                     <pip>
python                    3.5.3                         3
python-dateutil           2.4.2                     <pip>
pytz                      2015.7                    <pip>
PyYAML                    3.12                      <pip>
pyzmq                     16.0.2                    <pip>
qstrader                  0.0.1                     <pip>
requests                  2.18.1                    <pip>
requests-cache            0.4.12                    <pip>
requests-file             1.4.2                     <pip>
scipy                     0.17.0              np111py35_4
seaborn                   0.7.1                     <pip>
setuptools                27.2.0                   py35_1
simplegeneric             0.8.1                     <pip>
six                       1.10.0                    <pip>
testpath                  0.3.1                     <pip>
tornado                   4.5.1                     <pip>
traitlets                 4.1.0                     <pip>
urllib3                   1.21.1                    <pip>
vs2015_runtime            14.0.25123                    0
webencodings              0.5.1                     <pip>
wget                      2.2                      py35_0
wheel                     0.29.0                   py35_0
widgetsnbextension        2.0.0                     <pip>
```

**Comment by dieterjansen** [comment]
Hi penalvch, Adriaan1,

In the commit on 2017-04-13 a change was made to the qstrader/statistics/tearsheet.py modele which changed:

    plt.show()

to:

    plt.show(block=False)

This has the effect of showing the tearsheet briefly but immediately closing the plot window.

There may be a better way to override this behaviour but I just changed /home/user/venv/qstraderp3/lib/python3.5/site-packages/qstrader/statistics/tearsheet.py around line 637 back to “plt.show()”.  The path shown is where the tearship.py module is installed by convention on a Linux/virtualenv install.  With Windows/Anaconda or OS.X/Anaconda there will be a slightly different path.

This should allow you to see the tearsheet.  When you exit the plot viewer, the blocked backtest will continue and complete.

This needs to be resolved in a better way in the future (or the docco adjusted) but its a little beyond my skills to do so.

Cheers,
Dieter.


From: penalvch 
Sent: Saturday, June 17, 2017 6:15 AM
To: mhallsmoore/qstrader 
Cc: Subscribed 
Subject: [mhallsmoore/qstrader] Tearsheet figure is shown for less than a second, and then immediately disappears (#211)

What is expected to happen is when using Windows 10 to run buy_and_hold_backtest.py noted in https://www.quantstart.com/qstrader the tearsheet figure created is shown, and stays visible for review.

What happens instead is the backtest runs in Anaconda Prompt:

python buy_and_hold_backtest.py
Running Backtest...
---------------------------------
Backtest complete.
Sharpe Ratio: 0.25
Max Drawdown: 79.59%

(qstrader) c:\Anaconda3\envs\qstrader\examples>
but the figure window is created for less than a second, and then immediately disappears. Please see debug log:
debug.txt

Environment Setup

Windows 10 64-bit

Install Git:
https://github.com/git-for-windows/git/releases/download/v2.13.1.windows.1/Git-2.13.1-64-bit.exe

As per https://www.quantstart.com/knowledgebase/qstrader/installation/compatibility-issues-with-python-36x-pandas-and-qstrader install Anaconda via:
https://repo.continuum.io/archive/Anaconda3-4.2.0-Windows-x86_64.exe

Execute in Anaconda Prompt:

conda create --name qstrader
activate qstrader
conda install scipy==0.17.0
conda install wget
pip install git+https://github.com/mhallsmoore/qstrader.git
pip install -r https://raw.githubusercontent.com/mhallsmoore/qstrader/master/requirements.txt
Edit file:
C:\Anaconda3\envs\qstrader\Lib\site-packages\qstrader\settings.py

and change:
DEFAULT_CONFIG_FILENAME = '~qstrader.yml'

to:
DEFAULT_CONFIG_FILENAME = 'qstrader.yml'

Create blank qstrader.yml in:
C:\Anaconda3\envs\qstrader\examples\

Edit qstrader.yml and add:
CSV_DATA_DIR: C:\data
OUTPUT_DIR: C:\out

Execute in Anaconda Prompt:

mkdir c:\data
cd /d c:\data
python -m wget https://raw.githubusercontent.com/mhallsmoore/qstrader/master/data/SPY.csv
cd /d c:\Anaconda3\envs\qstrader\
mkdir examples
cd examples
python -m wget https://raw.githubusercontent.com/mhallsmoore/qstrader/master/examples/buy_and_hold_backtest.py
python buy_and_hold_backtest.py
conda list
# packages in environment at C:\Anaconda3\envs\qstrader:
#
backports.shutil-get-terminal-size 1.0.0                     <pip>
bleach                    2.0.0                     <pip>
certifi                   2017.4.17                 <pip>
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
cycler                    0.10.0                    <pip>
decorator                 4.0.9                     <pip>
entrypoints               0.2.3                     <pip>
enum34                    1.1.6                     <pip>
html5lib                  0.999999999               <pip>
idna                      2.5                       <pip>
ipykernel                 4.6.1                     <pip>
ipython                   4.2.0                     <pip>
ipython-genutils          0.1.0                     <pip>
ipywidgets                5.1.5                     <pip>
Jinja2                    2.9.6                     <pip>
jsonschema                2.6.0                     <pip>
jupyter-client            5.0.1                     <pip>
jupyter-core              4.3.0                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                1.5.3                     <pip>
mistune                   0.7.4                     <pip>
mkl                       11.3.3                        1
multipledispatch          0.4.9                     <pip>
munch                     2.1.1                     <pip>
nbconvert                 5.2.1                     <pip>
nbformat                  4.3.0                     <pip>
notebook                  5.0.0                     <pip>
numpy                     1.11.2                   py35_0
numpy                     1.10.4                    <pip>
pandas                    0.18.1                    <pip>
pandas-datareader         0.2.1                     <pip>
pandocfilters             1.4.1                     <pip>
path.py                   8.1.2                     <pip>
pexpect                   4.0.1                     <pip>
pickleshare               0.6                       <pip>
pip                       9.0.1                    py35_1
ptyprocess                0.5.1                     <pip>
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.0                     <pip>
python                    3.5.3                         3
python-dateutil           2.4.2                     <pip>
pytz                      2015.7                    <pip>
PyYAML                    3.12                      <pip>
pyzmq                     16.0.2                    <pip>
qstrader                  0.0.1                     <pip>
requests                  2.18.1                    <pip>
requests-cache            0.4.12                    <pip>
requests-file             1.4.2                     <pip>
scipy                     0.17.0              np111py35_4
seaborn                   0.7.1                     <pip>
setuptools                27.2.0                   py35_1
simplegeneric             0.8.1                     <pip>
six                       1.10.0                    <pip>
testpath                  0.3.1                     <pip>
tornado                   4.5.1                     <pip>
traitlets                 4.1.0                     <pip>
urllib3                   1.21.1                    <pip>
vs2015_runtime            14.0.25123                    0
webencodings              0.5.1                     <pip>
wget                      2.2                      py35_0
wheel                     0.29.0                   py35_0
widgetsnbextension        2.0.0                     <pip>

**Comment by penalvch** [comment]
Dieter, thanks for the quick WORKAROUND. Given it, I don't see a need to keep this issue open.
