### ISSUE TITLE
Stop backtest after 100% loss of capital

### ISSUE THREAD

**Issue by JamesKBowler** [mhallsmoore/qstrader#213]
Hi there!,
Just a thought, if the following code is added to the trading_session.py would it be ok?

```
    def _continue_loop_condition(self):
        if self.session_type == "backtest":
            if self.portfolio_handler.portfolio.equity > 0:
                return self.price_handler.continue_backtest
            else:
                return False
        else:
            return datetime.now() < self.end_session_time
```

This would allow the backtest to finish if the test fails and save on time when using shorter time frames.

Please let me know your thoughts.

Thanks

James

**Comment by femtotrader** [comment]
An other approach could be to raise a custom exception.

**Comment by mhallsmoore** [comment]
@JamesKBowler - I do like the idea of terminating the test once a zero balance has been achieved. I can't immediately see why anybody would want to continue running a strategy that has eliminated all capital, with the exception that they may want to introduce an extra cash balance later. Although admittedly this is unlikely!

@femtotrader - This is certainly an interesting approach, although one could say that exceptions are more designed for "exceptional" behaviour, in the programmatic sense. Not only that but the exception would then need to be handled in any client code and it is likely that it will be wrapped in something similar to @JamesKBowler's code. What do you think?

**Comment by JamesKBowler** [comment]
The capital loss does not necessarily need to be zero. For instance a total loss of 30% capital could exit the backtest. Just depends on how much one can stomach in terms of losses and of course rules one has set out prior to execution.
Also I feel some flexibility is required with this  parameter, as a profitable backtest my exit too soon.. say 31%.
Zero obviously needs to exit the backtest, regardless of what loss parameters are set above.

I agree, althought very possible introducing more capital at a losing strategy is not a good idea and unlikely. 

What's that saying ... ride winners and cut losers.

**Comment by mhallsmoore** [comment]
True...a sensible default would be 100% loss of capital triggering an exit. 

I am going to be working on the possibility of injecting capital into the system beyond the data of the backtest, as this gives a good reflection of how things work in a fund (e.g. with capital inflows and redemptions). I'd like to treat dividends in a similar manner, rather than assuming an immediate reinvestment.
