### ISSUE TITLE
Anaconda Windows version 

### ISSUE THREAD

**Issue by azuric** [mhallsmoore/qstrader#214]
How do I do this using conda on Win 10?

mkdir -p ~/qstrader/examples ~/data ~/out
cd ~/data
wget https://raw.githubusercontent.com/mhallsmoore/qstrader/master/data/SPY.csv
cd ~/qstrader/examples
wget https://raw.githubusercontent.com/mhallsmoore/qstrader/master/examples/buy_and_hold_backtest.py 

I get a syntax of the command is incorrect I assume cos this is for bash.

**Comment by mhallsmoore** [comment]
Hi azuric,

Indeed, you are correct these are commands for bash. Windows is not officially supported yet for QSTrader, but we will be making it compatible soon. 

In the meantime I suggest running it via Ubuntu or via Mac OSX (or anything that has a Unix-like environment).

Mike.
