### ISSUE TITLE
Why start_date and end_date are not optional?

### ISSUE THREAD

**Issue by Kroid** [mhallsmoore/qstrader#219]
In TradingSession, start_date & end_date - requires fields. But why? In price_handler they are optional values with None as default.

**Comment by JamesKBowler** [comment]
Are you looking at this part?

`        start = None
        end = None
        if self.start_date is not None:
            start = df.index.searchsorted(self.start_date)
        if self.end_date is not None:
            end = df.index.searchsorted(self.end_date)`

**Comment by JamesKBowler** [comment]
Are you looking at this part:?

```
        start = None
        end = None
        if self.start_date is not None:
            start = df.index.searchsorted(self.start_date)
        if self.end_date is not None:
            end = df.index.searchsorted(self.end_date)
```

**Comment by juliettejames** [comment]
This has been fixed and is present in the latest version.
Start and End dates can be changed in backtest.py

Thanks
