### ISSUE TITLE
error installing QSTrader on my MAC book pro 

### ISSUE THREAD

**Issue by mmourani** [mhallsmoore/qstrader#226]
hi, 

I was trying to run the following : 
pip install -r https://raw.githubusercontent.com/mhallsmoore/qstrader/master/requirements.txt

and I get the following error : 
Command "/Users/mmourani/venv/qstraderp3/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/3g/bns9h7ds6l57hpstx8p2kzlc0000gn/T/pip-build-a3o1sh9z/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/3g/bns9h7ds6l57hpstx8p2kzlc0000gn/T/pip-df49jlgg-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/mmourani/venv/qstraderp3/include/site/python3.6/scipy" failed with error code 1 in /private/var/folders/3g/bns9h7ds6l57hpstx8p2kzlc0000gn/T/pip-build-a3o1sh9z/scipy/

**Comment by JamesKBowler** [comment]
upgrade pip?

**Comment by mmourani** [comment]
pip not pip3. I just upgraded today to pip3

**Comment by mmourani** [comment]
with pip3 i get the bellow error now : 
Command "/opt/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-lo0n6qw1/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_a37u5u9-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-lo0n6qw1/scipy/

**Comment by gmahjub** [comment]
Getting the same issue on Macbook Pro, Minconda3 environment.

**Comment by tekalesachin** [comment]
For MacOS 

I have used Anaconda Navigator to installed below missing items on my qstrader environment

1. cython
2. gfortran_osx-64
3. libgfortran
