### ISSUE TITLE
Feature/discussion: Accounting, auditing, logging, trade-log?

### ISSUE THREAD

**Issue by ryankennedyio** [mhallsmoore/qstrader#23]
I'm unsure as to what an institutional setting would require and am only familiar with retail discretionary trade logs, but personally this would be most useful for debugging backtests (e.g. what exactly caused a big spike/dip ).

Probably a CSV file including every trade that had taken place would be the most useful way to do this? My alternate method for debugging has been pretty awful, "if timestamp == X: import pdb; pdb.set_trace()" and then poking around current positions.

I'm a bit sick of doing the above when debugging, so will probably work on this before any HDF5 integration. Can anyone include features that might be necessary for their own regulatory environments?

**Comment by ryankennedyio** [comment]
To ensure this has minimal impact on the rest of the system, I'm including it as an optional addition to the execution_handler, called a "compliance" component. The basic version will only log trades and store them in a CSV.

**Comment by ryankennedyio** [comment]
Have basic version completed:
https://github.com/ryankennedyio/qstrader/tree/compliance

However, running into https://github.com/mhallsmoore/qstrader/issues/27 which does drastically reduce the usefulness of this

**Comment by mhallsmoore** [comment]
I've just merged the Pull Request submitted for this. I'll also take a look at #27 at some stage.

**Comment by mhallsmoore** [comment]
I accidentally closed the issue, although there's a lot more we could do here, so I'll leave the conversation open!

**Comment by ryankennedyio** [comment]
Might close this for now until anyone comes up with "necessities" -- getting a lot of issues sitting in the board. Nice to close some out.
