### ISSUE TITLE
Installation Error to Matplotlib Mac

### ISSUE THREAD

**Issue by jonsariaatmadja** [mhallsmoore/qstrader#230]
Hi, 

I tried installing as per the instructions and it came with the following error:

RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ

Please help. Thanks!
Jon

**Comment by frankier234** [comment]
When setting up your virtual environment replace the command:

virtualenv --no-site-packages -p python3 .

with:

python -m venv .

source: https://matplotlib.org/faq/osx_framework.html#virtualenv

**Comment by frankier234** [comment]
You may also encounter an attribute error referring to 'FigureCanvasMac' when trying to run the code.  I believe this is caused by the default matplotlib backend.  I have found a work around which involves using the Agg backend.   Unfortunately the Agg backend is incompatible with interactive windows and therefore forces us to save the tearsheet as a png, none the less it enables us to carry out analyses!

Below are the amendments required:
At the very top of /statistics/tearsheet.py add the following two lines:

import matplotlib
matplotlib.use('Agg')

At the bottom of /statistics/tearsheet.py replace:

def save(self, filename=""):
        filename = self.get_filename(filename)
        self.plot_results

with

def save(self, filename=""):
        filename = self.get_filename(filename)
        self.plot_results(filename)

finally in trading_session.py replace:

    def start_trading(self, testing=False):
        """
        Runs either a backtest or live session, and outputs performance when complete.
        """
        self._run_session()
        results = self.statistics.get_results()
        print("---------------------------------")
        print("Backtest complete.")
        print("Sharpe Ratio: %0.2f" % results["sharpe"])
        print(
            "Max Drawdown: %0.2f%%" % (
                results["max_drawdown_pct"] * 100.0
            )
        )
        if not testing:
              self.statistics.plot_results()
        return results

with 

    def start_trading(self, testing=False, save=True):
        """
        Runs either a backtest or live session, and outputs performance when complete.
        """
        self._run_session()
        results = self.statistics.get_results()
        print("---------------------------------")
        print("Backtest complete.")
        print("Sharpe Ratio: %0.2f" % results["sharpe"])
        print(
            "Max Drawdown: %0.2f%%" % (
                results["max_drawdown_pct"] * 100.0
            )
        )
        if not testing:
            if save:
                self.statistics.save()
            else:
                self.statistics.plot_results()
        return results

**Comment by femtotrader** [comment]
You should avoid using Python from Mac default install.
You should install a scientific distribution of Python such as Anaconda Python https://anaconda.org/anaconda/python

**Comment by tanaytrivedi** [comment]
@frankier234 So the code you gave failed, mainly because there is no 'save' variable for the if statement to check:
`if save:`
What should I be putting in here to get this code functional? Should I just set it to false for now for it to plot?

**Comment by frankier234** [comment]
@tanaytrivedi You must also modify the argument list for the start_trading function such that it includes a default bool for save.  If you look in the modifications I have suggested that this is set to True such that an image is saved in your out folder after every backtest that is run.  You can see how the start_trading argument list should be configured below.

def start_trading(self, testing=False, save=True):

Let me know if this sorts your problem.

**Comment by tanaytrivedi** [comment]
@frankier234 thanks for the help, I figured this one out. Some help on #239 would be helpful now to get qstrader to run on my data.

**Comment by mhallsmoore** [comment]
Hi all,

Just to let you know that in the new version of QSTrader this issue will not be present any more!

Cheers,

-Mike.
