### ISSUE TITLE
Could not subscribe..for pricing

### ISSUE THREAD

**Issue by fbondeaux** [mhallsmoore/qstrader#233]
**I have an issue when I try to run:**
https://github.com/mhallsmoore/qstrader/blob/master/examples/moving_average_cross_backtest.py

**Error:**
Could not subscribe ticker abn001 as no data CSV found for pricing.
Could not subscribe ticker ing001 as no data CSV found for pricing.

**What I've done so far to make sure it reads the data well:**
I) Added a data file into the qstrader work file and I've put there two .csv files named abn001 and ing001;

II) Adapted the qstrader.yml:
---
CSV_DATA_DIR: rf/Users/Documents/BF/data
OUTPUT_DIR: rf/Users/Documents/BF/out
Where I've put two .csv files;

III) Tried to sort this piece of code out:
from qstrader.settings import SettingsDefault

class SettingsUserdefined(SettingsDefault):
    _CSV_DATA_DIR = "~/data"
    _OUTPUT_DIR = "~/qstrader"

conf = SettingsUserdefined()

**I've attached a print screen with what my data looks like.**
![schermafbeelding 2017-10-06 om 20 52 11](https://user-images.githubusercontent.com/32580007/31293684-517a771e-aad8-11e7-94d6-2e799f161c3c.png)

It would be nice if we would have a clear solution for this issue as I saw at a few times before. 
What I suggest is to modify this piece of code to read it directly from a path:
if __name__ == "__main__":
    # Configuration data
    testing = False
    config = settings.from_file(
        settings.DEFAULT_CONFIG_FILENAME, testing
    )
    tickers = ["abn001", "ing001"]
    filename = None
    run(config, testing, tickers, filename)

**Comment by fbondeaux** [comment]
Seriously, delete this 'backtester' from your machine. It's awful and the support is no where.

**Comment by JamesKBowler** [comment]
Hi @fbondeaux ,
Are you sure they are csv files? Not much information to go off if I am honest.

I agree the collaboration on this project is very low, no-one seems to be sharing any ideas, however, it is not awful back tester.

Could you provide more details, please? OS version, code snippings, screenshots?

Thanks

James

**Comment by fbondeaux** [comment]
@JamesKBowler 
Of course they are .csv files. I am not a stranger to trading or backtesting. 

I've created my own backtest framework in Python so I won't need qstrader any more.

For future reference: I would suggest that serious traders create their own framework. There is a lot of boilerplate code what makes modifying very hard. 

Take care.
