### ISSUE TITLE
Position size set with suggested_quantity in SignalEvent being ignored

### ISSUE THREAD

**Issue by dieterjansen** [mhallsmoore/qstrader#234]
I have been working on backtesting a simple strategy but am having trouble with the position size.  My code is supposed to take a single position in the DJIA but when I look at the tearsheet it is clear the positions are much larger than that.  Looking at the tradelog in ~/out/ shows a constant position size of 100 is being used.

My code was based on the moving_average_cross_backtest.py example which may be edited to reproduce the problem.  Running the code shows tradelog lines like:

        2002-02-08 00:00:00,AAPL,BOT,100,ARCA,24.03,1.0
        2002-08-14 00:00:00,AAPL,SLD,100,ARCA,15.17,1.0
        2003-07-15 00:00:00,AAPL,BOT,100,ARCA,19.61,1.0
        ...

Changing line 26 from:
        base_quantity=100
to:
        base_quantity=50
should result in a runlog like:

        2002-02-08 00:00:00,AAPL,BOT,50,ARCA,24.03,1.0
        2002-08-14 00:00:00,AAPL,SLD,50,ARCA,15.17,1.0
        2003-07-15 00:00:00,AAPL,BOT,50,ARCA,19.61,1.0
        ...

but we get:

        2002-02-08 00:00:00,AAPL,BOT,100,ARCA,24.03,1.0
        2002-08-14 00:00:00,AAPL,SLD,100,ARCA,15.17,1.0
        2003-07-15 00:00:00,AAPL,BOT,100,ARCA,19.61,1.0
        ...

as before.

It appears the suggested_quantity optional parameter in SignalEvent is not being honoured.

If this is correct it also suggests that a unit test should be added to check SignalEvents for sizes other than 100 units to pick up any future regressions.

**Comment by MagicEthan** [comment]
You should check position sizer. In default, any SignalEvent will be processed by position sizer and risk manager before it becomes an order event. So change the default_quantity in the default position sizer (if None it is the FixedPositionSizer). Besides, make sure to use your local qstrader package and pip uninstall qstrader in your python library (else you should edit the qstrader package in your local python library).
