### ISSUE TITLE
examples don't work out of the box

### ISSUE THREAD

**Issue by jacohn16** [mhallsmoore/qstrader#24]
Not sure if this was intentional (i.e.  you wanted user to add final touches), but it seems the examples don't work out of the box.  In particular I found:
1) requirements.txt was missing several packages
2) Statistics module is missing "SimpleStatistics" (see test_strategy_backtest.py)

**Comment by trb5me** [comment]
I'm looking at the same thing. Even if you change the name form SimpleStatistics to Statistics, the Statistics class doesn't have an update() method

**Comment by jacohn16** [comment]
Update:
I found if you just call the constructer (Statistics()), and comment out the methods calls to .update() in the backtester, then the backtest completes successfully.  I also had to comment out 
        #self.statistics.get_results()
        #self.statistics.plot_results()

And get_results() needs an implementation as well.  For now I just replaced with generate_results()  - possibly this is what its supposed to be in the first place.  But it seems the statistics code is incomplete, as there's nothing populating the equity curve file.

I am excited about where this project is going, so I might take a stab at fixing this up.  I can share my work if/when I get something working.

**Comment by jacohn16** [comment]
Update:
Sorry, didn't see the latest pull request.  This probably be resolved:
https://github.com/mhallsmoore/qstrader/pull/10

**Comment by mhallsmoore** [comment]
Apologies for not merging this sooner! I've been in Manchester for the last couple of days, but am heading back today.

I've just merged in Ryan's pull request, so I'll give it a proper test over the next couple of days when I'm back home. 

If anybody finds any issues in the meantime, let me know, and I'll get them resolved as well.
