### ISSUE TITLE
Run strategy on multiple instruments

### ISSUE THREAD

**Issue by 0x0Koda** [mhallsmoore/qstrader#241]
This is more of an architecture question than an issue. 
I want to run the same strategy on thousands of instruments (stocks). The strategies don't need to be aware of each other except for portfolio/risk/position sizing. 

Do i modify the strategy object (thinking the example MA crossover one) to handle multiple independent instruments, or is there a way to have many instances of the strategy object running but using the same tradingsession, portfolio etc objects. 

Are there any examples of this?

**Comment by gRittyKitty** [comment]
I'm probably not the best person to answer this. However, I think that you can do this either way. I don't have an example and I have not thought it all the way through. Somewhere, you will have to have a data structure that stores either all of the strategies or the relevant state conditions of those strategies within a single entity.
