### ISSUE TITLE
Sortino Ratio "Improvement"

### ISSUE THREAD

**Issue by gRittyKitty** [mhallsmoore/qstrader#242]
Thought you might want to take a look at this article on the "correct" way to calculate Sortino. I put it in quotes because de facto it may not make much difference. See [here](http://www.redrockcapital.com/Sortino__A__Sharper__Ratio_Red_Rock_Capital.pdf) and [here](https://www.rcmalternatives.com/2013/09/sortino-ratio-are-you-calculating-it-wrong/) The upshot is that the sortino calculated this way is a bit higher but may (or may not) serve a better normalization procedure. 

The reason why it came up for me is that I have adapted qstrader to my own needs (I implemented subset of features and changed the fill method) and had errors when I had only one drawdown. I was using a random test strategy with a tiny set of data points for testing.

I updated the sortino calc in performance.py to:
```
sortino_rets = returns.apply(lambda x: min(x,0))
return np.sqrt(periods)*(np.mean(returns))/np.std(sortino_rets)
```

Regardless, I thought the community here would be interested in the article on Sortino ratio calculation.

Edit: I am totally remiss without thanking you for posting qstrader. Thank you! It is great. I'm still pulling it all together.

**Comment by mhallsmoore** [comment]
Hi gRittyKitty,

Thanks for pointing this out! We'll be sure to consider this aspect for the new QSTrader version.

Thanks also for the kind words!

Cheers,

-Mike.
