### ISSUE TITLE
Post-start subscription to Tickers

### ISSUE THREAD

**Issue by gRittyKitty** [mhallsmoore/qstrader#244]
I'm looking at the [historic csv price handler](https://github.com/mhallsmoore/qstrader/blob/master/qstrader/price_handler/historic_csv_tick.py)

I'm sure that for nearly all backtests, that one is going to specify all the tickers initially. However, the class does provide for the ability to subscribe to more tickers after instantiation. 

For instance (don't mind my super-sophisticated stock tickers):

```
from mkt_data_mgr import MarketDataMgr
from event import TickEvent
import queue

eq = queue.Queue()
tickers = ['dum', 'dum2']
mkt = MarketDataMgr('/Users/ari/documents/development/backtester/', eq, tickers)
mkt.subscribe_ticker('dum3')
while mkt.continue_backtest:
    try:
        event = eq.get(False)
    except queue.Empty:
        mkt.stream_next()
```

I realize that I have adapted things and technically this is no longer strictly speaking qstrader code. But, it mostly is, and the subscribe_ticker method is the same. I think you'll find the same results if anyone runs within qstrader.

Anyway the results of this are that ticker 'dum3' does not show up in the stream. And this makes sense if we look at the __init__ code. 

```
        if init_tickers is not None:
            for ticker in init_tickers:
                self.subscribe_ticker(ticker)
        self.tick_stream = self._merge_sort_ticker_data()
```

It shows quite clearly that it is not sufficient to subscribe, but one must also merge it into the tick stream. Somehow this needs to be integrated from the outside. So, either there ought to be a "subscribe_multiple_tickers" or "subscribe_initial", or, alternatively, make it so that subscribe_ticker iteratively adds the new tickers to the tick_stream. 

Please let me know what you think. I've never contributed to coding an opensource project and I'm not sure of the protocol. I don't mind coding it, but want to make sure that there is interest in this change/fix. I have some others, too. Ive changed the execution handler to be more like an exchange with an order book and "matching engine" since I'm working with tick data. I don't mind posting it, but my code is now a bit different than qstrader. If there is interest, I can either post mine, or maybe shift my project to be a fork of qstrader.

**Comment by mhallsmoore** [comment]
Hi gRittyKitty,

Indeed you are correct - this is definitely an issue. 

I mentioned in a few other issues today that we're actually working on a "ground up" redevelopment of QSTrader, and one such reason is the need for subscribing tickers beyond the initial backtest start date.

This is clearly required for strategies such as long-term equities momentum, where certain ETFs would not have been available prior to the backtest initiation date.

We're handling this in the new version by completely separating the iteration over data from the event-loop. This means that new tickers can be added/removed easily via some additional logic, without affecting the event looping process.

We're likely to have the first version released by the end of 2017 or start of 2018, but this may to far in the future for your needs? If so, we can certainly discuss trying to append in your proposed changes into the current codebase.

Cheers,

-Mike.

**Comment by gRittyKitty** [comment]
Hi Mike,
I've already implemented these features. It ended up demanding a bit more, too. Once you have limit orders, then you have the potential for unfilled orders (I guess you could do IOC orders, but I did not think about that then). Once you have unfilled orders, there needs to be a way to cancel. Once you cancel without filling, then you need a way to let the strategy know whether it is in or out of a trade (my actions are asymmetric), so I created StrategyEvents for the portfolio_mgr to "talk" to the strategy_mgr. 
I've also implemented some logging features, a trading start time, trading end time, and a liquidate portfolio function.
It did not seem like too much until I see it written here. Anyway, like I said, I'm happy to share if there is interest. 
Ari
