### ISSUE TITLE
GARCH Optimization Problem in R

### ISSUE THREAD

**Issue by jonmilson** [mhallsmoore/qstrader#247]
I'm trying to fit a GARCH(1,1) model using rugarch library in R to predict S&P500 returns for the next 25 days. I have hard coded the ARIMA p and q to be 4 and 4 respectively for this example. However, each time I run this, it comes up as an optimization error.

Here is the code:

    `getSymbols("^GSPC",` from="2016-01-01")
    asset = diff(log(Cl(GSPC)))
    returns = as.numeric(asset)

    spec = ugarchspec(
        variance.model=list(garchOrder=c(1,1)),
        mean.model=list(armaOrder=c(
          4,4                                   
          ), include.mean=T),
        distribution.model="sged"
        )

    fit = ugarchfit(
      spec, returns, solver = 'hybrid')`

and here is the error:

    `Error in optim(init[mask], armaCSS, method = optim.method, hessian = 
    TRUE,  : 
     initial value in 'vmmin' is not finite`

**Comment by JamesKBowler** [comment]
Hi Jonmilson,
Is this issue related to QSTrader?
