### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by morris9795** [mhallsmoore/qstrader#250]
os:windows 7

there is something wrong in this step:
pip install git https://github.com/mhallsmoore/qstrader.git

I got the error message:
Collecting https://github.com/mhallsmoore/qstrader.git
  Downloading https://github.com/mhallsmoore/qstrader.git
     \ 102kB 251kB/s
Cannot unpack file C:\Users\MORRIS~1\AppData\Local\Temp\pip-qvbxhk_f-unpack\qstrader.git (downloaded from C:\Users\MORRIS~1\AppData\Local\Temp\pip-d1dwvi29-build, conte
nt-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of C:\Users\MORRIS~1\AppData\Local\Temp\pip-d1dwvi29-build

Can you help me ?

**Comment by estatic** [comment]
Hi @morris9795 

It seems you need to run installation on Anaconda as pip doesn't work sometimes for some reasons.

**Comment by mhallsmoore** [comment]
Hi @morris9795,

Thank you @estatic for the suggestion to use Anaconda.

I have now updated the installation procedure to allow ``pip install qstrader``, which should fix most problems if an Anaconda 3.7 environment is installed.

Please let me know if you have any further problems.

Kind regards,

Mike.
