### ISSUE TITLE
dates for the new release :)

### ISSUE THREAD

**Issue by andrewcz** [mhallsmoore/qstrader#252]
Was wondering if you guys had some dates for the new release.
Would just like to try it in some of my university work.
Super cool!
Best,
Andrew

**Comment by bnhede** [comment]
I am also interested . The margin feature is something i am hoping to get in the new version.
Kindly comment on its release.

**Comment by JamesKBowler** [comment]
Hi Mike/Team,
What are the latest developments, when do you think the updated version will be released?

Thanks

James

**Comment by mhallsmoore** [comment]
Hi all,

Apologies for the long delay in responding to this.

I released version 0.1.0 to PyPI about a week ago. You can now install it via ``pip install qstrader``. Also, I'm going to try and make a very small update release (0.1.1) soon to fix a few minor issues found in 0.1.0.

Regards,

Mike.
