### ISSUE TITLE
Windows installation error

### ISSUE THREAD

**Issue by Edulongo7** [mhallsmoore/qstrader#253]
Hi, I have tried to install QStrader, but got the following error:

C:\Users\Eduardo>pip install git+https://github.com/mhallsmoore/qstrader.git
Collecting git+https://github.com/mhallsmoore/qstrader.git
  Cloning https://github.com/mhallsmoore/qstrader.git to c:\users\eduardo\appdata\local\temp\pip-slk3r080-build
  Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/mhallsmoore/qstrader.git C:\Users\Eduardo\AppData\Local\Temp\pip-slk3r080-build
Cannot find command 'git'

Am I doing something wrong? Thank You. Eduardo

**Comment by JamesKBowler** [comment]
Seems to be a common problem with Windows.

https://www.google.co.uk/search?ei=x31oWpiYKMOAgQbA9LL4AQ&q=cannot+find+command+%27git%27+windows&oq=Cannot+find+command+%27git%27+wind&gs_l=psy-ab.3.0.0j0i22i30k1.1207.3211.0.4421.11.9.2.0.0.0.175.966.4j4.8.0....0...1c.1.64.psy-ab..1.7.669...0i20i263k1j33i160k1.0.GdA1tOAc9Lw
