### ISSUE TITLE
Datetime attribute in OrderEvent and SignalEvent classes

### ISSUE THREAD

**Issue by erenkeskus** [mhallsmoore/qstrader#254]
Hello,

I noticed that there are no attributes holding the time of the event in OrderEvent and SignalEvent classes in event.py.  The log contains this information, but since the algorithm is iterative, there is no way to hold on to it. 
I want to reach both and plot them against my price curve when I am runnig a backtest, so that I have a visual understanding of what is going on inside the strategy and risk manager. I would like to make alterations in tearsheet.py accordingly, as well. 
I hope I am not missing anything. 

Cheers, 
Eren

**Comment by JamesKBowler** [comment]
Hi @erenkeskus, do you mean in real time as the backtest is running?

Regards,
James
