### ISSUE TITLE
where is the file  '~/qstrader.yml' ?

### ISSUE THREAD

**Issue by royburns** [mhallsmoore/qstrader#260]
DEFAULT_CONFIG_FILENAME = '~/qstrader.yml'

**Comment by JamesKBowler** [comment]
what OS have you installed `qstrader` on?

On Linux my file is located at `/home/nonroot/qstrader.yml`, which is created from the `settings.py` file. 

Just use the `locate qstrader.yml` command on Linux.

**Comment by royburns** [comment]
windows10
