### ISSUE TITLE
Release and version numbering

### ISSUE THREAD

**Issue by femtotrader** [mhallsmoore/qstrader#267]
Hello,

qstrader currently don't have any release https://github.com/mhallsmoore/qstrader/releases

When doing software development it's generally a good idea to tag release with version numbering.
Ideally version numbering should follow semantic versioning https://semver.org/

https://en.wikipedia.org/wiki/Software_versioning

Doing this will help a lot readers of your books as they could be sure to use the right version of software (the same exact version that was used when writing your books)

Kind regards

**Comment by mhallsmoore** [comment]
Hi @femtotrader,

Thank you for the suggestion to use SemVer.

We had planned to utilise SemVer going forward with the new development version (https://github.com/mhallsmoore/qstrader/tree/development).

The first version for release will be 0.1.0.

Kind regards,

Mike.
