### ISSUE TITLE
Error while running buy_and_hold_backtest.py

### ISSUE THREAD

**Issue by RakeshP94** [mhallsmoore/qstrader#274]
I am trying to run `python buy_and_hold_backtest.py` but I am getting the following error:

 **File "buy_and_hold_backtest.py", line 7
     < !DOCTYPE html >
     ^
 SyntaxError: invalid syntax**

I have installed and followed all the relevant steps including creating the qstrader.yml file.

I am using Windows 10 and Anaconda with Python 3.7.

**Comment by briancappello** [comment]
Not sure what you did, but that error means you've got HTML in your Python. The [file in master](https://github.com/mhallsmoore/qstrader/blob/master/examples/buy_and_hold_backtest.py) looks fine, so I suspect this is on your end?

**Comment by RakeshP94** [comment]
> Not sure what you did, but that error means you've got HTML in your Python. The [file in master](https://github.com/mhallsmoore/qstrader/blob/master/examples/buy_and_hold_backtest.py) looks fine, so I suspect this is on your end?

I downloaded the files again and this seems to have solved this particular issue, though it raised a new one. Thanks for your help!
