### ISSUE TITLE
How to use qstrader with data from other countries?

### ISSUE THREAD

**Issue by RakeshP94** [mhallsmoore/qstrader#275]
For example, I have historical data stored in CSV for Indian stocks and indices. I cannot substitute these prices as it throws a 'cannot subscribe to ticker' error. Is there a way to make qstrader work with data from other countries?

**Comment by mhallsmoore** [comment]
Hi @RakeshP94,

Thank you for your question.

Could you provide an indicative sample, such as the header and one or two lines of the CSV data in question?

Kind regards,

Mike.
