### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by hlabcd** [mhallsmoore/qstrader#276]
I install QSTrader on my Windows 10 machine via Anaconda,and when I run pip install git+https://github.com/mhallsmoore/qstrader.git.it's just ok.it said"Successfully built qstrader
Installing collected packages: qstrader
Successfully installed qstrader-0.0.1",but when I run"pip install -r https://raw.githubusercontent.com/mhallsmoore/qstrader/master/requirements.txt",it say" BUILDING MATPLOTLIB
                matplotlib: yes [1.5.3]
                    python: yes [3.7.3 (default, Mar 27 2019, 17:13:21) [MSC
                            v.1915 64 bit (AMD64)]]
                  platform: yes [win32]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.16.2]
                  dateutil: yes [using dateutil version 2.8.0]
                      pytz: yes [using pytz version 2018.9]
                    cycler: yes [using cycler version 0.10.0]
                   tornado: yes [using tornado version 6.0.2]
                 pyparsing: yes [using pyparsing version 2.3.1]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [The C/C++ header for png (png.h) could not be
                            found.  You may need to install the development
                            package.]
                     qhull: yes [pkg-config information for 'qhull' could not be
                            found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: yes [using nose version 1.3.7 / using unittest.mock]
            toolkits_tests: yes [using nose version 1.3.7 / using unittest.mock]

    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: yes [installing, Qt: 5.9.6, PyQt: 5.9.6]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: yes [installing]

    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: no
                     latex: no
                   pdftops: no

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Lenovo\AppData\Local\Temp\pip-install-ygkupzj2\matplotlib\

(qstrader) C:\Users\Lenovo>pip install wheel
Requirement already satisfied: wheel in c:\users\lenovo\anaconda3\lib\site-packages (0.33.1)

(qstrader) C:\Users\Lenovo>pip install -r https://raw.githubusercontent.com/mhallsmoore/qstrader/master/requirements.txt
Collecting decorator==4.0.9 (from -r https://raw.githubusercontent.com/mhallsmoore/qstrader/master/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7d/ca/493b2377bf42d57bdd985c31975be3d2b500ad9079199cecb7633e8e2cde/decorator-4.0.9-py2.py3-none-any.whl
Collecting ipython==4.2.0 (from -r https://raw.githubusercontent.com/mhallsmoore/qstrader/master/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/c0/e0/9a9ea143c0fd508e3c294b78a04d187d1698df78009d0eb6d040c0d10e21/ipython-4.2.0-py3-none-any.whl
Collecting ipywidgets==5.1.5 (from -r https://raw.githubusercontent.com/mhallsmoore/qstrader/master/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/99/4b/ea6c47acee3bdee7a4fc56d7c97023e7011761f45899b3c88d7e70973996/ipywidgets-5.1.5-py2.py3-none-any.whl
Collecting ipython-genutils==0.1.0 (from -r https://raw.githubusercontent.com/mhallsmoore/qstrader/master/requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/6a/b3/4ce580020d6be73770d55515a65aec9ed5f3ea95f09e00300e53fc264218/ipython_genutils-0.1.0-py2.py3-none-any.whl
Collecting matplotlib==1.5.3 (from -r https://raw.githubusercontent.com/mhallsmoore/qstrader/master/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/75/4e/2374eed18ac34421ccd7b4907080abd3009e112ca2c11b100c18961312e0/matplotlib-1.5.3.tar.gz
    Complete output from command python setup.py egg_info:
    ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [1.5.3]
                    python: yes [3.7.3 (default, Mar 27 2019, 17:13:21) [MSC
                            v.1915 64 bit (AMD64)]]
                  platform: yes [win32]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.16.2]
                  dateutil: yes [using dateutil version 2.8.0]
                      pytz: yes [using pytz version 2018.9]
                    cycler: yes [using cycler version 0.10.0]
                   tornado: yes [using tornado version 6.0.2]
                 pyparsing: yes [using pyparsing version 2.3.1]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [The C/C++ header for png (png.h) could not be
                            found.  You may need to install the development
                            package.]
                     qhull: yes [pkg-config information for 'qhull' could not be
                            found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: yes [using nose version 1.3.7 / using unittest.mock]
            toolkits_tests: yes [using nose version 1.3.7 / using unittest.mock]

    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: yes [installing, Qt: 5.9.6, PyQt: 5.9.6]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: yes [installing]

    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: no
                     latex: no
                   pdftops: no

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Lenovo\AppData\Local\Temp\pip-install-zmurwsc9\matplotlib\

(qstrader) C:\Users\Lenovo>pip install qt5agg
Collecting qt5agg
  Could not find a version that satisfies the requirement qt5agg (from versions: )
No matching distribution found for qt5agg"

**Comment by Bonobo791** [comment]
@mhallsmoore I'm looking for an answer to this, too.

**Comment by mhallsmoore** [comment]
Hi @hlabcd and @Bonobo791,

I made some updates to the current codebase yesterday that upgraded the dependency versions to the latest available. The code should be compatible with Python 3.5, 3.6 and 3.7. The latter version is utilised by the latest Anaconda download.

Could you possibly try reinstalling with the new ``requirements.txt`` and let me know if there are any issues running the backtest?

Kind regards,

Mike.

**Comment by Bonobo791** [comment]
@mhallsmoore I'll let you know. Thanks!

**Comment by mhallsmoore** [comment]
Hi @Bonobo791,

Thanks for your reply.

Just to let you know that I've merged in the long-running new ``development`` branch into the ``master``, which will be the primary version of QSTrader going forward.

In order to maintain compatibility with the Advanced Algorithmic Trading ebook, as well as for those who have built backtesting systems off the previous version, we have kept this version (also recently updated to the latest Python package versions) on the ``advanced-algorithmic-trading`` branch, which can be found here: https://github.com/mhallsmoore/qstrader/tree/advanced-algorithmic-trading

The installation instructions have been recently tested so please let us know if you have any further issues.

Kind regards,

Mike.

**Comment by Bonobo791** [comment]
Thanks!
