### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by xiaoliangbuaa** [mhallsmoore/qstrader#278]
**after typing this cmd in terminal:

pip install -r https://raw.githubusercontent.com/quantstart/qstrader/master/requirements.txt

I got this error, and the complete error message is attached. Any help would be appreciated.**

  ERROR: Complete output from command /Users/tanjuju/anaconda3/envs/qstrader/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/mr/vm25w3r932g7yf1n06bby2k00000gn/T/pip-install-sf35ozbp/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/mr/vm25w3r932g7yf1n06bby2k00000gn/T/pip-wheel-we7tsi4d --python-tag cp37:
  ERROR: ============================================================================
  Edit setup.cfg to change the build [options[](url)](url)
...
[terminal_error.pdf](https://github.com/mhallsmoore/qstrader/files/3146520/terminal_error.pdf)

**Comment by mhallsmoore** [comment]
Hi @xiaoliangbuaa,

Yesterday I pushed up some changes to update the dependencies to the latest version for Python 3.5, 3.6 and 3.7.

If you try the installation procedure once more hopefully this will fix your issue.

Kind regards,

Mike.
