### ISSUE TITLE
Unclear on Position()'s accounting

### ISSUE THREAD

**Issue by trb5me** [mhallsmoore/qstrader#28]
Maybe I'm a little unclear on the vocab, but a fresh position shouldn't give massive unrealised pnls, right? Line 91 in position.py is part calculating unrealised_pnl, and it's subtracting a negative cost_basis. Here's a little example that's mostly plagiarized from the test in the same folder.

```
from qstrader.position.position import Position

position = Position(
            "SLD", "PG", Decimal('100'), 
            Decimal("77.69"), Decimal("1.00"), 
            Decimal('77.68'), Decimal('77.70')
        )
print(position.cost_basis)
print(position.avg_price)
print(position.total_sld)
print(position.unrealised_pnl) # 15537.00 which is  2*7768.5
print(position.realised_pnl)
```

**Comment by mhallsmoore** [comment]
Hi trb5me,

Thanks for pointing this out to me - I'll double check what was done here and amend.

Mike.

**Comment by trb5me** [comment]
Mike, 
I tried fixing what I could spot, and this was the pull request I submitted.
Taylor
