### ISSUE TITLE
HMM backtest problem (AttributeError: 'YahooDailyCsvBarPriceHandler')

### ISSUE THREAD

**Issue by ishest** [mhallsmoore/qstrader#282]
Hi,
when I run regime_hmm_backtest I get the message below:    

"... self.config.CSV_DATA_DIR, self.events_queue,
AttributeError: 'YahooDailyCsvBarPriceHandler' object has no attribute 'CSV_DATA_DIR'"

system: windows 10
python 3.6

**Comment by rudydreamer** [comment]
support@quantstart.com  I get some problem with AttributeError: 'YahooDailyCsvBarPriceHandler' object has no attribute 'CSV_DATA_DIR'"

**Comment by onahkenneth** [comment]
@ishest @rudydreamer 
Ensure to you set CSV_DATA_DIR environment variable in your .bash_profile, .bashrc or .profile files if your are using Linux
 See screenshot
<img width="515" alt="Screenshot_2020-01-10_at_20_27_45" src="https://user-images.githubusercontent.com/4136156/72176924-38682500-33e8-11ea-8c14-5e1c65ae2ea0.png">

**Comment by mhallsmoore** [comment]
Thanks @onahkenneth for the suggestion.

@ishest and @rudydreamer - Did this fix your issue?

**Comment by ishest** [comment]
> Thanks @onahkenneth for the suggestion.
> 
> @ishest and @rudydreamer - Did this fix your issue?

yep! Thanks!

**Comment by mhallsmoore** [comment]
Great!

Regards,

Mike.
