### ISSUE TITLE
ipython>=5.0.0

### ISSUE THREAD

**Issue by cero1010** [mhallsmoore/qstrader#311]
ERROR: ipykernel 5.2.1 has requirement ipython>=5.0.0, but you'll have ipython 4.2.0 which is incompatible.

**Comment by mhallsmoore** [comment]
Hi @cero1010,

This has also likely been fixed as part of the work for Issue #313 (https://github.com/mhallsmoore/qstrader/issues/313). 

Please let us know if you have any further problems.

Regards,

Mike.
