### ISSUE TITLE
compliance module: FileNotFoundError not available in Python 2

### ISSUE THREAD

**Issue by nwillemse** [mhallsmoore/qstrader#32]
Hi,

I'm running into this error that Python 2 doesn't recognise this exception. I guess it's only available in Python 3.

Is qstrader going to be coded for Python 3 only, or should we make it backwards compatible?

What's the best way to handle both python 2 and 3 in this case?

Thanks
Nick

**Comment by ryankennedyio** [comment]
Hey Nick,

My bad -- didn't check for backwards compatibility when I wrote it. I'll be 2 or 3 days away from finding time to add that.

I believe the entire system is designed to be compatible with both 2 and 3, is that right @mhallsmoore ?

**Comment by mhallsmoore** [comment]
Hi Nick,

Ryan is right - the project will be designed for both 2.7.x and 3.5.x compatibility. Admittedly I've been coding it in a 3.5.x environment, using a virtualenv on Ubuntu 14.04, but I will set up a 2.7.x local virtualenv and carry out all tests to date to make sure there are no hidden issues. Most of the time it's as simple as checking that the print statement becomes a print function, or that the correct queue module is imported, so it should be quite quick to check.

I'll close the issue when I'm happy that it's all working.

Mike.

**Comment by femtotrader** [comment]
Most Python libraries that want to be retro compatible with several versions of Python use a `compat.py` file.

https://www.google.fr/search?q=python+compat.py

Six can also help https://pythonhosted.org/six/

**Comment by femtotrader** [comment]
It's fixed by https://github.com/mhallsmoore/qstrader/pull/48
