### ISSUE TITLE
Can we have a boolean argument to suppress the events getting printed?

### ISSUE THREAD

**Issue by chatRG** [mhallsmoore/qstrader#334]
https://github.com/mhallsmoore/qstrader/blob/e3af73b457ba4aab8124d35bf7c11e020d7da740/qstrader/trading/backtest.py#L385

Thanks!

**Comment by mhallsmoore** [comment]
Hi @chatRG,

Apologies for the delay in response to your comment!

Yes, this is a good idea. Largely this has been done for ease of use for those getting up to speed with the backtester.

It will be pretty straightforward to add a boolean argument to suppress the print statements.

I'll leave the Issue open until I've added it to a subsequent release.

Kind regards,

Mike.

**Comment by mhallsmoore** [comment]
Thanks @simongarisch - now fixed with #338.
