### ISSUE TITLE
Error pip install qstrader

### ISSUE THREAD

**Issue by Mamakgooa** [mhallsmoore/qstrader#344]
Hi...I am struggling to install qstrader using command prompt. Any suggestions?

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by mhallsmoore** [comment]
Hi @Mamakgooa,

Would it be possible to let us know which operating system and/or Python environment you are utilising in an attempt to install QSTrader?

Also, if possible, could you post the full traceback that occurs when you attempt to install?

Kind regards,

Mike.

**Comment by blindemu** [comment]
Seeing the same issue, full message below, running on Windows 10:

`    ERROR: Command errored out with exit status 1:
     command: 'c:\users\--\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\--\\AppData\\Local\\Temp\\pip-install-3bdsnfj2\\matplotlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\--\\AppData\\Local\\Temp\\pip-install-3bdsnfj2\\matplotlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\--\AppData\Local\Temp\pip-install-3bdsnfj2\matplotlib\pip-egg-info'
         cwd: C:\Users\--\AppData\Local\Temp\pip-install-3bdsnfj2\matplotlib\
    Complete output (47 lines):
    ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [3.0.3]
                    python: yes [3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020,
                            22:45:29) [MSC v.1916 32 bit (Intel)]]
                  platform: yes [win32]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.18.1]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype
                            (freetype2\ft2build.h) could not be found.  You may
                            need to install the development package.]
                       png: no  [The C/C++ header for png (png.h) could not be
                            found.  You may need to install the development
                            package.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
                       agg: yes [installing]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                    macosx: no  [Mac OS-X only]
                 windowing: yes [installing]

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/freetype.htm for instructions to install
                            * freetype
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/libpng.htm for instructions to install png
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by mhallsmoore** [comment]
Hi @blindemu,

Thank you for sending over the error message. Could you let me know which Python environment you are using? Are you using Python directly or via Anaconda or similar?

Kind regards,

Mike.

**Comment by mhallsmoore** [comment]
While I have not tested this potential fix, it may be due to using ``matplotlib==3.0.3``, which is the version I've listed in ``requirements.txt``. If you install the latest version of matplotlib (e.g. run ``pip install matplotlib==3.3.3``) prior to running ``pip install qstrader``, this may fix the issue.

Kind regards,

Mike.

**Comment by jessemarder** [comment]
Hello,
I am getting the same issue. I am using Python 3.8.5 with Anaconda. I tried installing `pip install matplotlib==3.3.3` and it is installed. Full error:
`    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\jesse\.conda\envs\Quant\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jesse\\AppData\\Local\\Temp\\pip-install-v47_t047\\matplotlib_8db59cab6b3d4c25ac9e2e4c74c583dc\\setup.py'"'"'; __file__='"'"'C:\\Users\\jesse\\AppData\\Local\\Temp\\pip-install-v47_t047\\matplotlib_8db59cab6b3d4c25ac9e2e4c74c583dc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jesse\AppData\Local\Temp\pip-pip-egg-info-5zrlwm84'
         cwd: C:\Users\jesse\AppData\Local\Temp\pip-install-v47_t047\matplotlib_8db59cab6b3d4c25ac9e2e4c74c583dc\
    Complete output (43 lines):
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [3.0.3]
                    python: yes [3.8.5 (default, Sep  3 2020, 21:29:08) [MSC
                            v.1916 64 bit (AMD64)]]
                  platform: yes [win32]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.19.1]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype
                            (freetype2\ft2build.h) could not be found.  You may
                            need to install the development package.]
                       png: yes [Using unknown version found on system.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]
    
    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]
    
    OPTIONAL BACKEND EXTENSIONS
                       agg: yes [installing]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                    macosx: no  [Mac OS-X only]
                 windowing: yes [installing]
    
    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]
    
    ============================================================================
                            * The following required packages can not be built:
                            * freetype
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/freetype.htm for instructions to install
                            * freetype
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by jessemarder** [comment]
Hello @mhallsmoore ,

I am getting the same issue as @blindemu on Anaconda, Python 3.8.5 Windows 10. I have matplotlib version 3.3.3 installed. The error message only mentions a problem with Freetype, which I installed from their website (Complete package and sources). Do I need anything additional?

>   Using cached qstrader-0.2.1-py3-none-any.whl (75 kB)
Requirement already satisfied: Click==7.1.2 in c:\users\jesse\.conda\envs\quant\lib\site-packages (from qstrader) (7.1.2)
Collecting matplotlib==3.0.3
  Using cached matplotlib-3.0.3.tar.gz (36.6 MB)
Note: you may need to restart the kernel to use updated packages.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\jesse\.conda\envs\Quant\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jesse\\AppData\\Local\\Temp\\pip-install-_23npbat\\matplotlib_33c07560990d418a956ccaf84a088c72\\setup.py'"'"'; __file__='"'"'C:\\Users\\jesse\\AppData\\Local\\Temp\\pip-install-_23npbat\\matplotlib_33c07560990d418a956ccaf84a088c72\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jesse\AppData\Local\Temp\pip-pip-egg-info-oj441dbr'
         cwd: C:\Users\jesse\AppData\Local\Temp\pip-install-_23npbat\matplotlib_33c07560990d418a956ccaf84a088c72\
    Complete output (43 lines):
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [3.0.3]
                    python: yes [3.8.5 (default, Sep  3 2020, 21:29:08) [MSC
                            v.1916 64 bit (AMD64)]]
                  platform: yes [win32]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.19.1]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype
                            (freetype2\ft2build.h) could not be found.  You may
                            need to install the development package.]
                       png: yes [Using unknown version found on system.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]
    
    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]
    
    OPTIONAL BACKEND EXTENSIONS
                       agg: yes [installing]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                    macosx: no  [Mac OS-X only]
                 windowing: yes [installing]
    
    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]
    
    ============================================================================
                            * The following required packages can not be built:
                            * freetype
                            * Please check http://gnuwin32.sourceforge.net/packa
                            * ges/freetype.htm for instructions to install
                            * freetype
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by gnaleep** [comment]
> While I have not tested this potential fix, it may be due to using `matplotlib==3.0.3`, which is the version I've listed in `requirements.txt`. If you install the latest version of matplotlib (e.g. run `pip install matplotlib==3.3.3`) prior to running `pip install qstrader`, this may fix the issue.
> 
> Kind regards,
> 
> Mike.

this is not working
