### ISSUE TITLE
Tutorial on how to handle non time indexed bars

### ISSUE THREAD

**Issue by davidwynter** [mhallsmoore/qstrader#346]
The Equity class relies on time bars. Is it possible to use volume bars or dollar value bars with QSTrader? If it is it would be useful to have an example of this

**Comment by mhallsmoore** [comment]
Hi @davidwynter,

At this stage we only support homogeneously-sampled time-based OHLCV bars for the data.

By 'volume bars' do you refer to heterogeneously-sampled bars that all have a similar/identical volume over the time period?

Kind regards,

Mike.
