### ISSUE TITLE
Create conda package

### ISSUE THREAD

**Issue by zzhengnan** [mhallsmoore/qstrader#356]
@mhallsmoore Hi Michael. Would there be interest in creating a conda package for `qstrader` to serve as an alternative method of installation besides pip? 

The robustness of conda's dependency management could help with installation issues faced especially by Windows users, which is emerging as a theme based on a cursory look at the issue log.

Separately, the fact that you are _already_ recommending the Anaconda distro in the setup means there's no additional tooling needed on the user's end in order to install a conda package.
> The simplest approach is to download a self-contained scientific Python distribution such as the Anaconda Individual Edition

Curious to hear what you think. Thanks!

**Comment by mhallsmoore** [comment]
Hi @zzhengnan,

Thank you for your suggestion of creating a conda package. I imagine there would be a lot of interest in this, since, as you mention I do recommend Anaconda as the most straightforward way to get started!

I have to admit I've not built a conda package myself before previously, so would need to look up the process.

Cheers,

-Mike.

**Comment by zzhengnan** [comment]
Thanks for the reply, Michael. If you are open to it, I'm more than happy to help contribute to this feature. Let me know.

**Comment by zzhengnan** [comment]
Hope you don't mind, but I got the process started https://github.com/conda-forge/staged-recipes/pull/13843.

References:
- https://conda-forge.org/#add_recipe
- https://github.com/conda-forge/iscan-feedstock/blob/master/recipe/meta.yaml, which is the conda recipe for one of my own projects

**Comment by zzhengnan** [comment]
Now that https://github.com/conda-forge/staged-recipes/pull/13843 has been merged and the resulting [conda package created](https://anaconda.org/conda-forge/qstrader), I opened #359 to update the installation instructions.

**Comment by mhallsmoore** [comment]
Hi @zzhengnan,

Apologies for the delay in getting back to you about this. 

Thank you very much for taking the time to package up QSTrader into a conda package!

I've now merged the README.md PR.

Cheers,

-Mike.

**Comment by zzhengnan** [comment]
No problem at all. Glad to help :)
