### ISSUE TITLE
How should a pair/pool trading strategy be implemented?

### ISSUE THREAD

**Issue by Aaimek** [mhallsmoore/qstrader#369]
Hi,

First of all, thank you for your work on this great advanced tool.
I am new to it and I am wondering how a basic pair trading mean-reversion trading strategy should be implemented.
From the examples provided with the library and my reading of the source code, I didn't manage to get my head around how it could properly be implemented.

Help from anyone would be much appreciated,
If progress is made I would be happy to share a re-implementation of the code in [this article](https://www.quantstart.com/articles/kalman-filter-based-pairs-trading-strategy-in-qstrader/) if it is ever useful to anyone.

Cheers

**Comment by Aaimek** [comment]
This could be done by passing the prices of the assets as signals to the `AlphaModel` and then run the real signal logic in there, but this doesn't look right to me. I wil maybe try to do this

**Comment by datatalking** [comment]
Hi @Aaimek Let me know if you want help in working on that, I'm rebuilding a large chunk of my code this summer and this repo has good stuff so far.
