### ISSUE TITLE
Please provide SPY CSV file please !!

### ISSUE THREAD

**Issue by AgileQuant** [mhallsmoore/qstrader#371]
https://raw.githubusercontent.com/mhallsmoore/qstrader/master/data/SPY.csv 

Dear Author，
    I have check this project for years while still unable to run it due to lack of data file.  Please provide one data example. 

Best regards
Flashboy

**Comment by Helmsman-Lab** [comment]
https://finance.yahoo.com/quote/AGG/history?period1=1064880000&period2=1648944000&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true

https://finance.yahoo.com/quote/SPY/history?p=SPY
