### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by noowfel** [mhallsmoore/qstrader#375]
Hello, 

First of all I want to thank you for making this great tool available to everybody. I am currently reviewing backtesting libraries to select one. 
I was wondering if you guys plan on adding more documentation on the website https://www.quantstart.com/qstrader/ ? 
I mean more documentation on the functions of the library etc...

Thank you

**Comment by juliettejames** [comment]
Thanks for getting in touch.

There are several articles on the main site wihich explain inmore detail how some of the modules work. 
Check out this article [series](https://www.quantstart.com/articles/Event-Driven-Backtesting-with-Python-Part-I/) for more information.
