### ISSUE TITLE
SimulatedBroker Issue

### ISSUE THREAD

**Issue by rricco** [mhallsmoore/qstrader#376]
I have noted that the ABC class Broker contains an abstract method named 'get_portfolio_total_non_cash_equity' that is not contemplated in the subclass SimulatedBroker(Broker), however, the Exception NotImplementedError is not raised. Does anybody know the reason?

**Comment by juliettejames** [comment]
Thanks,

These methods were found to be superfluous and have been removed in QSTrader 0.2.6
