### ISSUE TITLE
Massive fail of the modules from qstrader

### ISSUE THREAD

**Issue by Trrtrrnch** [mhallsmoore/qstrader#378]
Hello everyone.

Im trying to test an strategy but most of the modules are not working/found.

All the commented modules are the ones which are not working (see pic)
![image](https://user-images.githubusercontent.com/70725997/161304382-4e1caa8c-06e5-452b-a6d0-0039e1b0483a.png)

The error message with everone of them is like that (see pic)
![image](https://user-images.githubusercontent.com/70725997/161304572-3b6196bf-e2c4-41dd-9a2c-4a82f39c53fb.png)

Ive just installed the library qstrader following the guide github.
The installation specifications are this (see pic)
![image](https://user-images.githubusercontent.com/70725997/161304928-3cb326ef-d564-4459-a31f-0eb51f469be7.png)

My anaconda and python version are (see pic)
![image](https://user-images.githubusercontent.com/70725997/161305143-23a43213-5502-48b2-b6cc-9418bd696e5f.png)

How can I fix this problem? I need that modules.

Thank you very much!

**Comment by elavender1** [comment]
Unfortunately, I'm having the same problem.  Did you use pip install qstrader or pip install git+https://github.com/mhallsmoore/qstrader.git@advanced-algorithmic-trading. 

It's disappointing I was trying to use this for a final project

**Comment by datatalking** [comment]
@elavender1 what IDE are you running this in, many times this is a pathing issue. Its installed but you need to tell your software where to find that module by adding the path to your bash profile.
