### ISSUE TITLE
Compatibility with python 3.11 -error when plotting

### ISSUE THREAD

**Issue by plm203** [mhallsmoore/qstrader#383]
I am discovering the qstrader package which seems excellent. But when trying to plot a tearsheet, for instance in the 60/40 example portfolio backtest, i get the error: « gridkw['gridOn'] = not self._major_tick_kw['gridOn']  KeyError: 'gridOn' »

Swtching back to python 3.8 corrects this and i get the expected plot. I would like to be able to run qstrader on python 3.11 (so as to use it together with other code which is for python 3.11), so if the only issue is with plotting i expect we can work around it in a reasonable amount of time. Curiously i have not found here this compatibility issue discussed. Could anyone comment ? Will qstrader be "ported" to python 3.11 ?

Thank you very much.

**Comment by juliettejames** [comment]
Fixed in versions >= 0.2.3

Please see chnage log for more details.
