### ISSUE TITLE
timestamp date format in 60-40 portfolio

### ISSUE THREAD

**Issue by vitaminccc** [mhallsmoore/qstrader#385]
Ran into an error in 60-40 portfolio example when doing backtesting and retrieving prices from Yahoo downloaded file. Seems to be the same issue as #377 but unanswered. Looks like date format in SPY/AGG downloaded files does not compile. Not sure what needs to be done to fix it.

ValueError: Asset price for "EQ:AGG" at timestamp "2003-09-30 21:00:00+00:00" is Not-a-Number (NaN). This can occur if the chosen backtest start date is earlier than the first available price for a particular asset. Try modifying the backtest start date and re-running.

**Comment by colin-evers** [comment]
Same problem here........

**Comment by maxkdann** [comment]
Me too

**Comment by juliettejames** [comment]
Fixed in latest version. Please see change log.
