### ISSUE TITLE
Click version requirement

### ISSUE THREAD

**Issue by intStupid** [mhallsmoore/qstrader#388]
Hi,

When installing I found out there is a requirement of Click==7.1.2. Many of my used package will require Click >= 8.0. I wonder if there is anything preventing I use Click 8.0 instead.

**Comment by juliettejames** [comment]
Hi,

We have just tested using click 8.1 with Python 3.9, 3.10, 3.11 and 3.12.  

We can confirm that there should be no issues with upgrading to Click 8.1.

We will issue a new release of the QSTrader package to update the requirements for Click.

Thanks for getting in touch.
