### ISSUE TITLE
settings.py might accept ~ (home dir)

### ISSUE THREAD

**Issue by femtotrader** [mhallsmoore/qstrader#40]
Hello,

Home user directory shortcut `~` is not accept as a valid directory in `settings.py`

Running
```
$ python qstrader/examples/test_strategy_backtest.py
``` 

with this settings file

```python
CSV_DATA_DIR="~/data/random/"
OUTPUT_DIR="~/qstrader/"
```

raises

```
FileNotFoundError: [Errno 2] No such file or directory: '~/qstrader/tradelog_2016-06-22'
```

`os.path.expanduser` might help https://docs.python.org/3/library/os.path.html#os.path.expanduser

It may be cleaner to create an inherited class for settings
with methods to get `CSV_DATA_DIR`, `OUTPUT_DIR` with `~` expanded

Kind regards

**Comment by femtotrader** [comment]
Something like

in `settings_default.py`

```python
import os

class SettingsDefault(object):
    _CSV_DATA_DIR = "~/data"
    _OUTPUT_DIR = "~/qstrader"

    @property
    def CSV_DATA_DIR(self):
        return os.path.expanduser(self._CSV_DATA_DIR)

    @property
    def OUTPUT_DIR(self):
        return os.path.expanduser(self._OUTPUT_DIR)
```

in `settings.py`

```python
from settings_default import SettingsDefault

class Settings(SettingsDefault):
    _CSV_DATA_DIR = "~/my_cache"
    _OUTPUT_DIR = "~/my_qstrader"
```

**Comment by dieterjansen** [comment]
I made a similar sort of change suggestion for the logging path handling in QSForex in the following pull request:

    https://github.com/mhallsmoore/qsforex/pull/39

In that I detect the file location in what I understand to be a pretty general way (independent of how the process was started) and then derive the directory of the logging config file (also in a platform independent way, I hope).

The effect was to prevent the logging error if you start trading.py in the way described in the QSForex readme.md .

Using normpath seems sensible to maximise platform independence.

Hope that helps in some way.

**Comment by femtotrader** [comment]
An other approach could be to use a JSON, a INI or a YAML configuration file.

It will be better easier for packaging.

**Comment by femtotrader** [comment]
Closed by https://github.com/mhallsmoore/qstrader/pull/48
