### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by femtotrader** [mhallsmoore/qstrader#43]
Same as

https://github.com/mhallsmoore/qsforex/issues/9
https://github.com/mhallsmoore/qsforex/issues/20

It will be easier for packaging to have settings as configuration file
see https://github.com/mhallsmoore/qstrader/issues/40

**Comment by femtotrader** [comment]
Packaging is done
but registering is still to do

**Comment by mhallsmoore** [comment]
I've not actually registered a Python package before - do you have a good handle on the process? I'll be looking it up regardless, as it will be a lot nicer to simply say "pip install qstrader"!

**Comment by femtotrader** [comment]
Yes I have done this several times.
But maybe we should consider to make an organization (you are owner of course)... you can of course publish under your own name also this first version

You need a `~/.pypirc`

```
$ cat ~/.pypirc
[distutils] # this tells distutils what package indexes you can push to
index-servers = pypi
    pypi # the live PyPI
    pypitest # test PyPI

[pypi]
repository:http://pypi.python.org/pypi
username:yourpypiusername
password:yourpassword

[pypitest]
repository:https://testpypi.python.org/pypi
username:yourpypiusername
password:yourpassword
```

Register on pip

```
$ python setup.py register
```

Upload (sources, binaries...)
```
#python setup.py sdist bdist upload # sources an binaries
python setup.py sdist upload
```

**Comment by femtotrader** [comment]
Of course you first need to create an account following:

https://pypi.python.org/pypi?%3Aaction=register_form

**Comment by mhallsmoore** [comment]
We should have a discussion about versioning of the package. I do not want to give the impression that QSTrader is ready for production usage yet. It is definitely still within an alpha stage.

Perhaps the first version should be 0.0.1. Then we can make minor point releases for bug-fixes (0.0.x), as usual and the major point releases (0.x.x) for bigger features. The version numbers themselves (x.x.x) should only be changed for drastic revisions to the codebase and major new features.

What do we think?

**Comment by femtotrader** [comment]
I think it's too early for registering.
I think for example that Strategy API might (at least) be stabilized before registering
see for example in
https://github.com/femtotrader/femtotrading/blob/master/femtotrading/strategy/moving_average_cross.py
I have `on_init`, `on_tick`, `on_bar`...
There is also default parameters for strategy...
We shouldn't loose too much time on this. There is so many things to do before.

`pip install git+https://github.com/mhallsmoore/qstrader.git` should work for pressed people

**Comment by ryankennedyio** [comment]
Documenting the API's, Modules and some kind of architecture diagram to show the flow of information through the system will be very useful -- I think that should still be done as an alpha stage. Finalising these would be a good stage to move into a Beta.

In terms of more thorough documentation, which we can probably put together as we move into beta, I'm a fan of [Slate](https://github.com/lord/slate).

I'll start scribbling out an architecture diagram too, I'll probably just use [Canva](https://www.canva.com/) and invite @mhallsmoore and @femtotrader in as collaborators?

**Comment by femtotrader** [comment]
Thanks @ryankennedyio 
Documenting is something very important.
Most Python projects use ReadTheDocs http://www.readthedocs.io/
it can use Markdown syntax
https://read-the-docs.readthedocs.io/en/latest/getting_started.html#in-markdown

What is interesting is that doc is build remotely

I don't know Slate but it seems to also support Markdown syntax (which is nice because simple)
Building doc remotely is probably a key feature to have!

I'm not a native english speaker so it may be hard for me to write very correct english doc.

Never heard of Canva it seems to be an online drawing tool.
Great idea! Sometimes schematics are much better to understand concepts than long prose!

**Comment by ryankennedyio** [comment]
Yep, Slate is Markdown. Fairly nice to use and I think very attractive.

Canva is a cool little Aussie startup that's doing well so far. I think they allow collaborative drawings, so that will be useful for us. Schematics are good, gives the overview in 10 seconds, where reading can take 15 minutes.

**Comment by bzillins** [comment]
I would also suggest https://www.draw.io as a possible diagram candidate.

I have previously used the service when diagramming out a table structure
to hold historic option price data and found it very useful.

**Comment by mhallsmoore** [comment]
Hi all,

I'm going to close this issue now that QSTrader is in PyPI.

Regards,

Mike.
