### ISSUE TITLE
No default settings file

### ISSUE THREAD

**Issue by mhallsmoore** [mhallsmoore/qstrader#49]
@femtotrader - Now that the majority of the qstrader source lives under the /qstrader directory, we need to include a default settings.py in order for the strategies to "work out of the box".

I'm not too sure of the changes to the codebase as of yet (I'm still working through them), so I was wondering if you'd be happy adding a Pull Request with a default settings file?

**Comment by mhallsmoore** [comment]
Ahhh...I see it is actually in qstrader/settings.py. I'm just having some trouble running the strategy test code again. I'll try and sort this out.

**Comment by mhallsmoore** [comment]
When I run "strategy_backtest.py" I receive this traceback:

```Could not subscribe ticker GOOG as no data CSV found for pricing.
Traceback (most recent call last):
  File "examples/strategy_backtest.py", line 68, in <module>
    main(settings.DEFAULT, testing=False)
  File "examples/strategy_backtest.py", line 28, in main
    csv_dir, events_queue, tickers
  File "/home/mhallsmoore/venv/qstrader/lib/python3.4/site-packages/qstrader-0.0.1-py3.4.egg/qstrader/price_handler/price_handler.py", line 59, in __init__
  File "/home/mhallsmoore/venv/qstrader/lib/python3.4/site-packages/qstrader-0.0.1-py3.4.egg/qstrader/price_handler/price_handler.py", line 84, in _merge_sort_ticker_data
  File "/home/mhallsmoore/venv/qstrader/lib/python3.4/site-packages/pandas/tools/merge.py", line 812, in concat
    copy=copy)
  File "/home/mhallsmoore/venv/qstrader/lib/python3.4/site-packages/pandas/tools/merge.py", line 845, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate```

The problem, as far as I can tell is that in qstrader/settings.py, the SettingsDefault is correctly coded, but somehow even when I modify this file locally the _CSV_DATA_DIR attribute is not changing, as if it's being cached somewhere else.

Any ideas, @femtotrader? Is there something I'm missing about how you've restructured the code?

Cheers,

Mike.

**Comment by femtotrader** [comment]
You just need to
```python
from qstrader import settings
```

```python
config = settings.DEFAULT is default settings
```

```python
config = settings.TEST is settings for continuous integration
```

they all have a `CSV_DATA_DIR` attribute and a OUTPUT_DIR attribute

You can bypass default settings by defining 2 environment variables:

`QSTRADER_CSV_DATA_DIR` and `QSTRADER_OUTPUT_DIR`

You can also create your own (inherited configuration class)


```python
class SettingsUserdefined(SettingsDefault):
    _CSV_DATA_DIR = "~/data"
    _OUTPUT_DIR = "~/qstrader"

conf = SettingsUserdefined()
```

so that `~` is automatically expanded...

**Comment by femtotrader** [comment]
If you create a `~/data` directory with data inside and an empty `~/qstrader` directory
you shouldn't get any issue.

**Comment by mhallsmoore** [comment]
Great - I'll take a look at this over the next few days and write some more up to date documentation for the README.md. I'll also have a look through getting it put into a package, at which point the installation docs will be a lot clearer.

**Comment by femtotrader** [comment]
Good idea.

**Comment by femtotrader** [comment]
I had 2 requirements pyyaml http://pyyaml.org/wiki/PyYAMLDocumentation to parse this kind of file and Munch it's a dot accessible dict https://github.com/Infinidat/munch
so you access key of a dict like attribute of an object... a very convenient library !

**Comment by femtotrader** [comment]
Maybe we can close this
