### ISSUE TITLE
Enable CI and change badge link

### ISSUE THREAD

**Issue by femtotrader** [mhallsmoore/qstrader#51]
(just a reminder)

Travis need to be enable for this repository

Badge link should also be changed in `README.md`

from

[![Build Status](https://travis-ci.org/qstraders/qstrader.svg?branch=master)](https://travis-ci.org/qstraders/qstrader)

    [![Build Status](https://travis-ci.org/qstraders/qstrader.svg?branch=master)](https://travis-ci.org/qstraders/qstrader)

to

    [![Build Status](https://travis-ci.org/mhallsmoore/qstrader.svg?branch=master)](https://travis-ci.org/mhallsmoore/qstrader)

[![Build Status](https://travis-ci.org/mhallsmoore/qstrader.svg?branch=master)](https://travis-ci.org/mhallsmoore/qstrader)

**Comment by mhallsmoore** [comment]
Ok, I've just signed up to Travis CI, have enabled the qstrader repo in Travis and have modified and pushed the Build Status badge in README.md. I'm just testing both the Travis service through "Webhooks & Services" as well as looking at the Build Status badge on the qstrader repo homepage.

I'll close this when I'm happy it's working.

**Comment by mhallsmoore** [comment]
It says that the build is now passing. Are you happy that we can close this or have I missed some steps?

**Comment by femtotrader** [comment]
Yes we can close this
