### ISSUE TITLE
Bid/ask values for ticker %s are not available from the PriceHandler.

### ISSUE THREAD

**Issue by femtotrader** [mhallsmoore/qstrader#55]
`$ nosetests -s -v tests/test_price_handler.py`

ticker doesn't appear in this message

in `price_handler.py` - `HistoricCSVPriceHandler.get_best_bid_ask`

**Comment by femtotrader** [comment]
https://github.com/mhallsmoore/qstrader/blob/95a95559d327419b873e7bcb2f43451b9755cfa7/qstrader/price_handler/price_handler.py#L124

missing: `% ticker`

**Comment by mhallsmoore** [comment]
Good spot! Thanks for noticing. I'll amend.

**Comment by femtotrader** [comment]
More exactly you replace

```python
            print(
                "Bid/ask values for ticker %s are not "
                "available from the PriceHandler."
            )
```

with

```python
            print(
                "Bid/ask values for ticker %s are not "
                "available from the %s." % (ticker, self.__class__.__name__)
            )
```

**Comment by mhallsmoore** [comment]
I think this was carried out in the PR I merged this morning, so I'll close this.

**Comment by femtotrader** [comment]
Yes you can track this searching "Bid/ask values for ticker"
https://github.com/mhallsmoore/qstrader/search?utf8=%E2%9C%93&q=Bid%2Fask+values+for+ticker
found
https://github.com/mhallsmoore/qstrader/blob/aa39e8ded56fc658a5a316c857d623f4e3488c86/qstrader/price_handler/price_handler.py
click on "Blame"
search "Bid/ask values for ticker"
and found it was carried out by this PR https://github.com/mhallsmoore/qstrader/commit/bffc1a15f5634b49848c6aa741495646044138b0
