### ISSUE TITLE
How to plug live data stream data.

### ISSUE THREAD

**Issue by muke5hy** [mhallsmoore/qstrader#62]
I created my simple strategy and tested it with backtesting, as in we have in example. Now I would like to test the same strategy with streaming data. 
How and where to plug it. 

Can any one give simple class structure to begin with.

**Comment by femtotrader** [comment]
What you want is called paper trade.

I see 3 kind of trading session :
- backtest (historical data, simulated portfolio)
- paper trade (realtime data, simulated portfolio)
- live trade (realtime data, real portfolio)

I don't see in current code base such distinctions. So PR will be great.

A good idea could be to rename  `qstrader/backtest` to `qstrader/trading_session`

create in `__init__` an abstract class `AbstractTradingSession` with abstract method `run`

create `paper_trade.py`  and `live_trade.py` with inherited class (`PaperTrade` and `LiveTrade`) from `AbstractTradingSession

All these class will have to implement this `run` method...

`PaperTrade` code is similar to `Backtest` so in fact `PaperTrade` could be inherited from `Backtest`
and be nearly an empty class.

You will have to write your price handler according your broker and pass this price handler to your `PaperTrade` code.

A good idea could first to execute a `PrintStrategy` to print ticks... and go beyond after.

**Comment by muke5hy** [comment]
Awesome will try to implement it.
