### ISSUE TITLE
Example CSV Compliance might use UTC to avoid DST issue

### ISSUE THREAD

**Issue by femtotrader** [mhallsmoore/qstrader#64]
See https://github.com/mhallsmoore/qstrader/blob/master/qstrader/compliance/compliance.py#L51

```python
self.csv_filename = "tradelog_" + datetime.datetime.today().strftime("%Y-%m-%d") + ".csv"
```

should be replaced by

```python
today = datetime.datetime.utcnow().date()
self.csv_filename = "tradelog_" + today.strftime("%Y-%m-%d") + ".csv"
```

**Comment by mhallsmoore** [comment]
You can make a PR if you want, or I'll do it for the next release?

**Comment by femtotrader** [comment]
Please do

**Comment by femtotrader** [comment]
But please first enable CI !

**Comment by mhallsmoore** [comment]
Indeed, my apologies for not being able to work on QSTrader over the last few days - I've been busy writing chapters for the AAT book!

**Comment by ryankennedyio** [comment]
Thanks @femtotrader this PR could also do with including the "event time" issue for backtested dates.

I'll fix this and that and do a PR on the weekend. Finally some spare time coming up!!

**Comment by mhallsmoore** [comment]
I think this is complete now as I merged @ryankennedyio's PR this morning.
