### ISSUE TITLE
Limit orders.

### ISSUE THREAD

**Issue by ryankennedyio** [mhallsmoore/qstrader#69]
So, rather than always executing market orders, I imagine longer term (1min+) strategies will get a lot of benefit from being able to set a limit order a few ticks below market price on instruments `[a...m]`. As our orders are filled, the risk manager can pull excess limit orders accordingly. I know that manually just buying market all the time is a great way to throw good money, and can't imagine that automated trades would be too different.

As a rough example:
Say we want no more than 10 positions in our portfolio (set by an `equal_weight_position_sizer`). $100k capital, so position sizer will give $10k to each position.
As we run a strategy, we find 30 instruments that we want to long. We set 30 limit orders 3 ticks down from market. Every time we get a fill, we remove 3 limit orders (ish). At the end we're looking for a fill on 1 stock and we've got maybe 3 limit orders sitting in the bid stack.

All of the above figures are obviously open to being shuffled around. Interesting exercise for those inclined would be optimising these parameters with a self reinforced ML algorithm.

Realise this will open a new can of worms in terms of complexity, so I'd rather have most other aspects of the system nailed before this. It will involve a lot more work in the risk management & position sizing classes.

One risk is that the algorithm might "self-select" stocks that are about to turn against us if the limit order is set too far down. If it's just right, it should be similar in effect to market orders, but it would be easier to overcome brokerage & slippage this way.

Imagine a major difficulty in simulation is that a limit order is only filled a portion of the time when the stock trades at the set limit. Will also need to account for one of my pet hates, partial fills (got a 30% fill yesterday on something and then it gapped up 23% this morning --- hoorah. Edge cases like that will be a pain for an algorithm to deal with).

Any opinions?

**Comment by femtotrader** [comment]
Bracket orders are also great feature to have.
https://www.interactivebrokers.com/en/trading/orders/bracket.php

**Comment by mhallsmoore** [comment]
This brings up interesting questions regarding which limit orders are removed (due to ordering/randomness) and how to simulate this in an effective manner such that we don't heavily overfit the data to the past price histories.

I agree it adds some new complexity, but it makes the point that the PositionSizer and RiskManager should have completely up to date information on both market prices and the state of the current portfolio (this was always the intention anyway).

**Comment by ryankennedyio** [comment]
I agree 100% that limit orders could lead to very dangerous overfitting for backtests.

Removal of other limit orders is probably best left to the user's implementation. I imagine it should be the responsibility of the `RiskManager` to ensure the capital will be placed in instruments that are well diversified, so I'd lean toward pulling orders in similar sectors.

For the purposes of explaining it to users simply, I think random pulling of limit orders is OK. Or we can ignore this for the "example" modules.

Simulating fills will be really difficult. I think whatever we do should have some random change over time, which could simulate roughly how the algorithm would work in more/less liquid environments. Won't be too realistic, but it should help indicate how well an algorithm copes with these changes.

I think my `PositionSizers` and `RiskManagers` have almost always ended up with a reference to the `PortfolioHandler`, which is clean enough.

**Comment by femtotrader** [comment]
Partial fill could be simulated using order book history... but that's probably a quite hard to find data.

**Comment by ryankennedyio** [comment]
Order book history is horrifyingly expensive.

Might be worth streaming live market updates from IB (I think they offer some market depth?) for a few days and somehow track people's fills. Cancellation further complicates this...

I don't think a perfectly accurate backtest would be necessary here. If we stick to the conservative side for midcap size stocks, our backtests should lean toward a "worst-case" which I think is safe.

**Comment by mhallsmoore** [comment]
Yeah, going down the route of using order book data is verging on institutional level work! Not that it wouldn't be useful, but it will add a lot of complexity to the codebase, especially for those who might simply be interested in classic "close-to-close" style analysis.

I think a better approach, re the expense of data, would be to simulate order books and then test strategies with adjusted statistical parameters to see how differing (simulated) order book dynamics affect strategies.
