### ISSUE TITLE
Code coverage with Coveralls.io

### ISSUE THREAD

**Issue by mhallsmoore** [mhallsmoore/qstrader#70]
Coveralls.io: https://coveralls.io/

This looks good - it's a free to use service for open source repos (a la Travis) that gives us a code coverage percentage, as well as a badge to place next to the "test passing" badge on the README. It should encourage both:

* Development of more unit tests if the percentage is low
* More usage of the software if the percentage is high

What does everyone think? @femtotrader, @ryankennedyio?

**Comment by femtotrader** [comment]
We have local code coverage thanks to `coverage` and it's executed in CI build but you can add it if you want.

**Comment by ryankennedyio** [comment]
I think it's a great way to "suggest" we write better unit test coverage. If we have above as per @femtotrader , that seems fine. Haven't done enough of it with Python but coverage in my other projects is really helpful.

**Comment by femtotrader** [comment]
I think this can now be closed.
