### ISSUE TITLE
YAML package to use in requirements.txt?

### ISSUE THREAD

**Issue by mhallsmoore** [mhallsmoore/qstrader#71]
@femtotrader  - I've just looked at the requirements.txt file after trying to install the latest dependencies (munch, enum34 etc) and we have a line:

`yaml>=3.11`

On my system this fails with:

`Downloading/unpacking yaml>=3.11 (from -r requirements.txt (line 19))
  Could not find any downloads that satisfy the requirement yaml>=3.11 (from -r requirements.txt (line 19))`

It looks like there is no "yaml" package specifically, but rather we need to use pyyaml: http://stackoverflow.com/questions/14261614/how-do-i-install-the-yaml-package-for-python

If you're happy for me to do so, I'll change this in the requirements.

**Comment by femtotrader** [comment]
It's an issue

we need pyyaml not yaml

**Comment by femtotrader** [comment]
A mistake from my side! Sorry

**Comment by mhallsmoore** [comment]
I also didn't have libyaml-dev installed on Ubuntu, so I've just added that. It failed at compilation. Although it's still not appearing in my "pip freeze". Odd!

**Comment by femtotrader** [comment]
What does 

`apt-get install libyaml-dev`

**Comment by mhallsmoore** [comment]
Yeah, that's what I did. Although there are lot of C compilation warnings about pointer types. Perhaps most worrying is that I received a yellow warning of:

`Could not find .egg-info directory in install record for pyyaml`

When I tried to pip install pyyaml subsequent to the installation of libyaml-dev package.

I'll keep trying!
