### ISSUE TITLE
Bad class name usage

### ISSUE THREAD

**Issue by femtotrader** [mhallsmoore/qstrader#74]
class named `Test...` are for unit tests.
it's a bad idea to name them like this because it leads to confusion between example implementation of an abstract class and unit tests.

https://github.com/mhallsmoore/qstrader/search?utf8=%E2%9C%93&q=class+Test&type=Code

`TestPositionSizer` -> `FixedPositionSizer`

(default quantity might also be a parameter for `__init__`)

I also suggest to put abstract class in a `base.py` and each implementation in a different file.

It could be a good idea to name abstract class `Abstract...` (this is quite common in Julia... and help a lot to understand code)

Other rename

`TestRiskManager` -> `ExampleRiskManager`

`TestStrategy` -> `ExampleStrategy`
`TestCompliance` -> `ExampleCompliance` or `CsvCompliance`

I miss probably some others

**Comment by mhallsmoore** [comment]
Yes, this is definitely a good idea. That was poor choice of naming on my part!

I'll amend this.

**Comment by ryankennedyio** [comment]
Agree with the `Abstract` convention for base classes.
