### ISSUE TITLE
Using relative imports instead of absolute

### ISSUE THREAD

**Issue by femtotrader** [mhallsmoore/qstrader#75]
There is a lot of absolute imports and that's not necessary to do this

Example
https://github.com/mhallsmoore/qstrader/blob/master/qstrader/portfolio_handler/portfolio_handler.py

`from qstrader.order.order import SuggestedOrder`

could be (using relative imports)

`from ..order import SuggestedOrder`

**Comment by mhallsmoore** [comment]
@femtotrader - If you're happy making a PR for this, I'll incorporate it over the weekend or early next week?

**Comment by femtotrader** [comment]
Please first merge https://github.com/mhallsmoore/qstrader/pull/78
