### ISSUE TITLE
README.md badge to show Python versions a la Zipline?

### ISSUE THREAD

**Issue by mhallsmoore** [mhallsmoore/qstrader#77]
Does anybody know the correct mechanism to include Python version badges in the same vein as Quantopian have done for the Zipline project on their README? https://github.com/quantopian/zipline

**Comment by femtotrader** [comment]
They can do it because it's [registered on PyPi](https://github.com/mhallsmoore/qstrader/issues/43).

See https://raw.githubusercontent.com/quantopian/zipline/master/README.rst (it's a reStructuredText format file... not Markdown)

They are using http://shields.io/ badges.

**Comment by mhallsmoore** [comment]
Great... once we decide to go ahead and register (which I think we'll leave as per your suggestion in the other issue) I'll get these added.

**Comment by mhallsmoore** [comment]
This has now finally been done! Version 0.1.1 (the next release) will include a few more useful development badges.
