### ISSUE TITLE
CSV compliance minor issue

### ISSUE THREAD

**Issue by femtotrader** [mhallsmoore/qstrader#79]
Might remove
https://github.com/mhallsmoore/qstrader/blob/master/qstrader/compliance/compliance.py#L52

        self.csv_filename = "tradelog_" + datetime.datetime.today().strftime("%Y-%m-%d") + ".csv"
        self.csv_filename = "tradelog_" + today.strftime("%Y-%m-%d") + ".csv"

This was probably because of this morning big merge.

**Comment by mhallsmoore** [comment]
I presume this was merged with the PR?

**Comment by femtotrader** [comment]
Yes so I'm closing
