### ISSUE TITLE
Serialize results

### ISSUE THREAD

**Issue by femtotrader** [mhallsmoore/qstrader#82]
Hello,

it will be a good idea to store results into file.
So that we will be able to display again equity / drawdown plots...
and also get a DataFrame showing when trades occur in an interactive way (IPython...) after running a backtest.

Serialization can be done using Pickle.

An other option could be to store results to HDF5 files.

Maybe we should consider to build something on top of PyPET (in order to avoid reinventing a "squared wheel") https://pypet.readthedocs.io/en/latest/manual/introduction.html#getting-started

Kind regards

**Comment by ryankennedyio** [comment]
This would also be useful for instances where you're running QSTrader on either a headless server or a cloud server.

**Comment by femtotrader** [comment]
This would also be useful to see results of a same strategy with different parameter settings.

Plotting might be done with an other library (Bokeh or something else) to provide some features like zoom in / zoom out / pan ...

**Comment by femtotrader** [comment]
Hickle may also be considered https://github.com/telegraphic/hickle
but we should first have a look at Python 3 support
see https://github.com/telegraphic/hickle/issues/8

**Comment by femtotrader** [comment]
Other solution to consider:
Feather https://github.com/wesm/feather

**Comment by femtotrader** [comment]
Here is a PR that save statistics in a Pickle file.
Loading example is performed in a IPython notebook and equity curve is plot using Bokeh.
