### ISSUE TITLE
Performance: Significant degradation as bars & positions increase

### ISSUE THREAD

**Issue by ryankennedyio** [mhallsmoore/qstrader#91]
Backtesting a daily bar strategy with about 200 tickers. Involves a monthly rebalance of the portfolio.

Performance starts off at ~5,000 bars per second and fairly quickly degrades down to 2,000 bars after 3 years worth. The degradation happens quickly at first, then levels out once it gets really bad (in terms of time taken, not in terms of computational complexity. In complexity terms, it gets even worse over time, but it's taking slower to get worse -- if that makes sense).

I've done some solid digging and determined that it's because we keep reference to closed out positions in order to calculate portfolio values. This starts to get pretty deep into the core of qstrader, so it's well worth it for us to discuss the options and resolve this correctly.

If I simply do this at the end of `portfolio._modify_position()`, I can keep a steady 5,000 bars/sec through the entire backtest, regardless of size. That's ideal.
```
if self.positions[ticker].quantity == 0:
    self.positions.pop(ticker)
```
Obviously the test goes out the door because we can no longer calculate market value, as we've lost the `position.realised_pnl` used to calculate `portfolio.equity`. But the speed is good!!!

To prove this is the issue (and how I found it), here are two profiling results:
#### Currently
![not-removing-empty-positions](https://cloud.githubusercontent.com/assets/11158006/16950616/5b751cbe-4e00-11e6-874b-e75a0296a909.png)

#### After removing closed positions
![removing-empty-positions](https://cloud.githubusercontent.com/assets/11158006/16950622/68d7a520-4e00-11e6-9b67-2deaab6a9b01.png)

I think I ran a different length backtest the second time -- much longer (68s instead of 49s). 
Wanted to prove to myself that the performance was now constant as the problem set increased.
Can see that the obvious `portfolio.py` block is now reasonably consistent with the rest of the system.

An option to explore might be keeping some kind of reference object that should be kept to aggregate the value of closed-out positions. The issue, I think, is pretty obvious when seen; every backtest event causes us to go through and find the realised_pnl for every closed out position. The number of closed positions is ever increasing, leading to the degradation over time.

**Comment by femtotrader** [comment]
Hi @ryankennedyio ,

I'm quite happy to see that you are measuring backtest speed in term of bars/s or ticks/s
(and so we can see now how speed evolve over time)

I love this profiling tool... what is it ?

**Comment by ryankennedyio** [comment]
@femtotrader 

The tool is `runsnakerun` -- I had to use it with Python2.7, I don't think it's maintained anymore. 

First I ran the profiler by doing 
`python -m cProfile -o output.profile <file-to-run> <args>`

Then just run `runsnake` and open the output file. It's pretty neat!


The bars/s is really useful, very obvious way to see when any hiccups in speed happen.

**Comment by femtotrader** [comment]
Thanks @ryankennedyio I didn't know this tool

Unfortunately it doesn't work with Python 3.5

```
$ python --version
Python 3.5.2 :: Anaconda 4.1.1 (x86_64)
$ pip install runsnakerun
Collecting runsnakerun
  Using cached RunSnakeRun-2.0.4.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-zu1lt_rq/runsnakerun/setup.py", line 12
        except ImportError, err:
                          ^
    SyntaxError: invalid syntax
```

I have found snakeviz https://jiffyclub.github.io/snakeviz/ but I haven't try it.

**Comment by mhallsmoore** [comment]
This is great profiling work - I was going to be doing some myself, but it looks like you've beaten us to it! ;-)

RunSnakeRun looks really useful. I was wondering whether we could try and get it working, as a separate project, for Python 3.5? It might be a very useful tool for the general community.

**Comment by femtotrader** [comment]
Not sure if it helps but Quantopian uses now [bottleneck](http://berkeleyanalytics.com/bottleneck/release.html) (when available) see `https://github.com/quantopian/qrisk/pull/8`

**Comment by ryankennedyio** [comment]
Bringing the design solution discussion away from #90, so that issue can remain on topic for Statistics.

@nwillemse feedback here would be appreciated, if there's anything else you think you'll need accessible from the scope of Statistics classes, we'll see if it can be provided cleanly.


My line of thought at the moment;

Statistics Base class can provide an optional method, `store_position(position)`, that will be given a closed-out position. This also allows more complex Statistics implementations to plot entry & exit points from a trade (almost, we don't track entry timestamp as part of Position, it's only stored in Compliance output).


A few things still a little hazy, but it's becoming clearer.

* It should gracefully handle the case where Statistics doesn't have store_position() implemented (e.g. Simple class).
* As `Portfolio` pops a position, it attempts to store the position into Statistics.
* As `Portfolio` pops a position, it should also "crystalise" the PnL from that position and store it as a member variable of the Portfolio.
* Compliance and Statistics may start to functionally overlap -- not a fan.


Will draw out a diagram of the whole system tomorrow, which should help new people and also help us think about how to add new features/functionality.

The thing I don't like about the above is that the Portfolio now needs to "know about" Statistics. I'd like to avoid that if possible, as the Portfolio already has enough "links" to other moving parts of the system. I hope this won't add complexity to tests. I guess diagrams will help us visualise that and see if there's any obvious alternatives.

I also don't like that Positions are spread across the Portfolio and Statistics (Open and Closed), as well as current equity/cash totals. Though I guess conceptually, a real portfolio is only considered to be the current, live book.


How does everyone think of the above? Any obvious shortcomings, limitations, etc? Last thing I want is to do this and in 6 months realise it should be done differently, so all input appreciated.

**Comment by femtotrader** [comment]
Hi @ryankennedyio ,

You might have a look at https://github.com/mhallsmoore/qsforex/issues/43
You might also be interested by https://www.quantopian.com/posts/a-framework-to-manage-bracket-orders-with-sl-tp-and-additional-features-trailingstop-breakeven-expiration-and-advanced-statistics (see source code)
We need to store opened trades in an ordered dict ("trades") and move closed traded to an other ordered dict ("history").

Kind regards

**Comment by nwillemse** [comment]
@ryankennedyio 

I spend some time today to just look at all the parts of qstrader and how they interact.  I diagram would be awesome for everyone trying to get a big picture overview of how the program actually works and where to contribute.

I agree that somehow `Portfolio` needs to send a message to `Statistics` about open/closed positions.  Maybe `Portfolio` only needs to manage the open positions, and Statistics manages the closed positions.   Also, need to handle the last trade when it is still open at the end of backtest.

I can also see compliance and statistics having overlapping functionality.  

I am going to start prototyping a new statistics sub-class and see how it goes.

Comments/ideas welcome!

**Comment by ryankennedyio** [comment]
Progress. Tests pass, but $1 off on the `test_portfolio.py` method.

https://github.com/mhallsmoore/qstrader/compare/master...ryankennedyio:closed-positions?expand=1

**Comment by femtotrader** [comment]
Backtest speed with Quantopian / zipline is around 20'000 bars/s
https://www.quantopian.com/posts/display-backtest-speed-in-bars-slash-s-1

**Comment by ryankennedyio** [comment]
Are they single threaded @femtotrader  ?

**Comment by femtotrader** [comment]
I think so

**Comment by ryankennedyio** [comment]
Impressive, that's pretty quick. I know qstrader could do that multithreaded on a quad core machine, but to be that fast on a single process would be nice. @femtotrader do you think you could run a profile on Zipline?

We have some easy savings to be made only doing `update_portfolio()` once per-time-period (or longer), also casting datetimes explicitly. If we moved to multiprocess, the bars/s number scales almost linearly with the number of cores, but at the cost of complexity and more restrictions on communications between parts of qstrader.

**Comment by mattage86** [comment]
> 
> 
> Bringing the design solution discussion away from #90, so that issue can remain on topic for Statistics.
> 
> @nwillemse feedback here would be appreciated, if there's anything else you think you'll need accessible from the scope of Statistics classes, we'll see if it can be provided cleanly.
> 
> My line of thought at the moment;
> 
> Statistics Base class can provide an optional method, `store_position(position)`, that will be given a closed-out position. This also allows more complex Statistics implementations to plot entry & exit points from a trade (almost, we don't track entry timestamp as part of Position, it's only stored in Compliance output).
> 
> A few things still a little hazy, but it's becoming clearer.
> 
>     * It should gracefully handle the case where Statistics doesn't have store_position() implemented (e.g. Simple class).
> 
>     * As `Portfolio` pops a position, it attempts to store the position into Statistics.
> 
>     * As `Portfolio` pops a position, it should also "crystalise" the PnL from that position and store it as a member variable of the Portfolio.
> 
>     * Compliance and Statistics may start to functionally overlap -- not a fan.
> 
> 
> Will draw out a diagram of the whole system tomorrow, which should help new people and also help us think about how to add new features/functionality.
> 
> The thing I don't like about the above is that the Portfolio now needs to "know about" Statistics. I'd like to avoid that if possible, as the Portfolio already has enough "links" to other moving parts of the system. I hope this won't add complexity to tests. I guess diagrams will help us visualise that and see if there's any obvious alternatives.
> 
> I also don't like that Positions are spread across the Portfolio and Statistics (Open and Closed), as well as current equity/cash totals. Though I guess conceptually, a real portfolio is only considered to be the current, live book.
> 
> How does everyone think of the above? Any obvious shortcomings, limitations, etc? Last thing I want is to do this and in 6 months realise it should be done differently, so all input appreciated.

Did anyone ever publish a class diagram, or any diagrams, on QSTrader?
