### ISSUE TITLE
TkAgg backend problem with Mac OS X / Why should we force backend ?

### ISSUE THREAD

**Issue by femtotrader** [mhallsmoore/qstrader#92]
Hello,

When I run an example I get (now) many errors because of TkAgg backend

```python
$ python examples/buy_and_hold_backtest.py
objc[1826]: Class TKApplication is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk and /Users/femto/anaconda/lib/libtk8.5.dylib. One of the two will be used. Which one is undefined.
objc[1826]: Class TKMenu is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk and /Users/femto/anaconda/lib/libtk8.5.dylib. One of the two will be used. Which one is undefined.
objc[1826]: Class TKContentView is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk and /Users/femto/anaconda/lib/libtk8.5.dylib. One of the two will be used. Which one is undefined.
objc[1826]: Class TKWindow is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk and /Users/femto/anaconda/lib/libtk8.5.dylib. One of the two will be used. Which one is undefined.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/femto/anaconda/lib/python3.5/site-packages/matplotlib/backends/tkagg.py", line 22, in blit
    id(data), colormode, id(bbox_array))
_tkinter.TclError: invalid command name "PyAggImagePhoto"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/femto/anaconda/lib/python3.5/tkinter/__init__.py", line 1550, in __call__
    return self.func(*args)
  File "/Users/femto/anaconda/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 283, in resize
    self.show()
  File "/Users/femto/anaconda/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 355, in draw
    tkagg.blit(self._tkphoto, self.renderer._renderer, colormode=2)
  File "/Users/femto/anaconda/lib/python3.5/site-packages/matplotlib/backends/tkagg.py", line 30, in blit
    id(data), colormode, id(bbox_array))
_tkinter.TclError
alloc: invalid block: 0x1196c7e90: 10 0
Abort trap: 6
```

It seems that some other people face this issue
https://www.google.com/search?q=Class+TKApplication+is+implemented+in+both+%2FSystem%2FLibrary%2FFrameworks%2FTk.framework%2FVersions%2F8.5%2FTk&oq=Class+TKApplication+is+implemented+in+both+%2FSystem%2FLibrary%2FFrameworks%2FTk.framework%2FVersions%2F8.5%2FTk&aqs=chrome..69i57.331j0j7&sourceid=chrome&ie=UTF-8#q=Class+TKApplication+is+implemented+in+both+/System/Library/Frameworks/Tk.framework/Versions/8.5/Tk&tbs=qdr:m

I don't know exactly the reason of this... but removing

```python
try:
    matplotlib.use('TkAgg')
except:
    pass
```

in `qstrader/statistics/simple.py`

fixed this issue!

So I wonder why should we force backend ?

I think it's a user decision to use one backend or an other one

Here is my current available backends for Matplotlib

```python
$ python -c "import matplotlib; print(matplotlib.rcsetup.all_backends)"
['GTK', 'GTKAgg', 'GTKCairo', 'MacOSX', 'Qt4Agg', 'Qt5Agg', 'TkAgg', 'WX', 'WXAgg', 'CocoaAgg', 'GTK3Cairo', 'GTK3Agg', 'WebAgg', 'nbAgg', 'agg', 'cairo', 'emf', 'gdk', 'pdf', 'pgf', 'ps', 'svg', 'template']
```

A user can force to use a given backend using a config file named `~/.matplotlib/matplotlibrc`
with

```
backend : Qt4Agg
```

**Comment by mhallsmoore** [comment]
Indeed - I think this might have been "legacy" code that was added in. I used to develop solely on a Macbook Air, which has an old version of Mac OS X (10.7.* I believe). Nowadays I use Ubuntu (although still only 14.04), so it's less of an issue.

I completely agree we should not be forcing the backend.

**Comment by femtotrader** [comment]
What is odd is that I came up to this issue only today ! so I think Continuum probably break something with conda.

**Comment by nwillemse** [comment]
I have had this issue on my mac for a while now. Using python 2.7.  I was unable to find a solution yet...running qstrader on linux now.

**Comment by femtotrader** [comment]
Here is my Python version

```
$ python --version
Python 3.5.2 :: Anaconda 4.1.1 (x86_64)
```
