### ISSUE TITLE
Roadmap Inquiry: Options and Futures

### ISSUE THREAD

**Issue by canada4663** [mhallsmoore/qstrader#96]
Folks - 

First - super pumped you guys are working on this.  I'm following it closely - been reading Mike's blog for years.  Thanks for your efforts!  At some point I'll jump in and help... for now I'm working on my coding/unit testing skills as I build a manahl/arctic based data repository to make it easy to do research/etc as well as as a source for backtesting eventually. 

I am curious if your roadmap includes equity/futures options and futures capability?  If so, do you have any thoughts or direction on how you'd thread this in?

Ryan

**Comment by ryankennedyio** [comment]
Bit of a discussion going on here for reference :)

https://github.com/mhallsmoore/qstrader/issues/31

**Comment by canada4663** [comment]
Oops! Thanks - I will chime in there!

**Comment by femtotrader** [comment]
You might also have a look at https://github.com/mhallsmoore/qstrader/issues/34

**Comment by michaeljohnbennett** [comment]
I read with interest recently you were redesigning the framework and wanted to know how it would handle options or at least would it be possible to handle data/instruments/options being added to the algo to trade based on your Strategy/Algo reading an indicator on the underlying for instance?

In options trading you have a huge universe of options to trade but need the underlying and perhaps some other data to make the decision on what to trade. Most OSS engines don't seem to have this ability apart from zipline to some extent with its universe selection/pipelines but its so unbearably slow and only tradeable via Quantopian it's a non starter.

So do you think the framework could handle this strategy execution mode without substantial rewriting of functionality?

**Comment by SteffenNa** [comment]
Hi guys. Same interest here. I am also looking for a backtest engine with live trading capability with IB that can handle Options (Future and Equity Index options). I am delighted to hear that you are working on a system that goes beyond the typical moving average crossover strategy on US equities. It would be really refreshing and extremely helpful if your new platform would be able to handle a professional options strategy in a way that newly listed options can be traded by the strategy without having to be added manually. So can only second what michaeljohnbennet said.

**Comment by michaeljohnbennett** [comment]
Anyone have something to add to this?

**Comment by mhallsmoore** [comment]
Hi all,

I realise this is an old issue, however, now that I've released v0.1.0 to PyPI it is probably worth commenting on.

Since the new version is designed for long-only equities strategies the next major task is to integrate a mechanism for short sales along with more sophisticated approaches to portfolio and risk management.

Unfortunately this means that realistic derivatives trading simulation is likely to be some way off.

Regards,

Mike.
