### ISSUE TITLE
Where to log of each transaction done? 

### ISSUE THREAD

**Issue by muke5hy** [mhallsmoore/qstrader#98]
I am running a custom Strategy on minute data here is flow which I follow.  I have minute data in mongodb
1. Pass list of instruments which needs to be backtested. 
2. Define date range say 30 days. 
3. Loop through each day and pass instruments to Backtest.
4. This loop generates different Statistics for each loop, as I am calling it in a loop 

```
for execute_date in dates:
        run(config, testing, tickers, filename, execute_date)
```

I want to log each buy and sell activity along with its bar values. Where should I log this? 
Should I log while placing order in Strategy ?

**Comment by drex91** [comment]
QSTrader comes with an example compliance module which is able to log the trade activity. See [compliance/example.py](https://github.com/mhallsmoore/qstrader/blob/master/qstrader/compliance/example.py). 

You could take inspiration from the  _record_trade(self, fill):_  function such that the bar values are also logged to the trade CSV log. However I think the  SIGNAL, ORDER and FILL events need to be amended to include the bar data such that this can be propagated from the strategy to the execution_handler being used.

**Comment by muke5hy** [comment]
When I run the backtest only one entry goes in csv file.

**Comment by drex91** [comment]
Are you using the default _buy_and_hold_ strategy? If so, this is correct since the instrument transacted only once - bought on the first market event and retained for the whole duration of the backtest.
