### ISSUE TITLE
A command line interface to download data

### ISSUE THREAD

**Issue by femtotrader** [mhallsmoore/qstrader#99]
A command line interface to download data is necessary.

[pandas-datareader](http://pandas-datareader.readthedocs.io/en/latest/) provides Yahoo, Google data but doesn't provide for now a CLI to download and save data into CSV or XLS.

I opened an issue on pdr side https://github.com/pydata/pandas-datareader/issues/213 and did a PR to "fix" it  https://github.com/pydata/pandas-datareader/pull/214

I don't know exactly when this PR will be merged (I can merge it but I'd prefer other pydata member review it and merge it).
Moreover I don't know when a new release will be planned.

Maybe we should keep this code here (but name it differently `qstrader_download` for example).

@mhallsmoore @ryankennedyio your opinion ?

**Comment by femtotrader** [comment]
see also https://github.com/mhallsmoore/qstrader/issues/106

**Comment by ByteJuggler** [comment]
Just a brief note as Im away on holiday and replying on phone, been a
lurker here for some time with the intent of getting involved. Re data
downloader, I took over a python app some years ago ("pyq") that may serve
as inspiration and can download historical data from yahoo (o,h,l,c) and
oanda (close prices) as well as fetch live current quotes,  for a given
list of tickers.  Data is cached to prevent needless round trips.

If you google "^dji csv stackoverflow" (without the quotes) the top link
should be a question on Stackoverflow where I suggested pyq and described
pyq a bit more fully.

Walter

**Comment by femtotrader** [comment]
Thanks @ByteJuggler 
I had a look at https://code.launchpad.net/~wprins/python-pyq/trunk
it's currently only Python 2.
Could you move this project to GitHub and add Python 3 support ?
Maybe this project could be merged with Pandas DataReader also (maybe later) ?

**Comment by femtotrader** [comment]
@ByteJuggler 
Here is my Python 2/3 version of python-pyq
https://gist.github.com/femtotrader/2620c310002e961a37a2b84987cd0d45
Need some unit tests, continuous integration, PEP8 checking with flake8 ...

**Comment by ByteJuggler** [comment]
Thanks! Ill move the code to github and merge your changes etc once I'm
back. (We're returning  tomorrow.)

On 25 Jul 2016 12:24 p.m., "femtotrader" <notifications@github.com> wrote:

@ByteJuggler <https://github.com/ByteJuggler>
Here is my Python 2/3 version of python-pyq
https://gist.github.com/femtotrader/2620c310002e961a37a2b84987cd0d45
Need some unit tests, continuous integration, PEP8 checking with flake8 ...

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mhallsmoore/qstrader/issues/99#issuecomment-234917056>,
or mute the thread

**Comment by ByteJuggler** [comment]
I have finally got around to migrating the bzr repo (such as it is) to git and merged femotrader's Python 2/3 enhancements (print, urllib2->requests etc.)  

Repo is here:  https://github.com/ByteJuggler/pyq

Thanks again for your changes, they are things that should've been done a long time ago.  Agree on other points you make.  (Re PEP8 checking -- did that way back when when I took over the project so it ought not to be too bad but yes, agree.)

**Comment by femtotrader** [comment]
Thanks @ByteJuggler
